version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 9.0
  pre_build:
    commands:
      - dotnet restore
  build:
    commands:
      - dotnet publish -c Release -o ./app
artifacts:
  files:
    - '**/*'