using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Mottrist.Domain.LookupEntities;

namespace Mottrist.Repository.EntityFrameworkCore.Configurations.GeographySchemaConfiguration
{
    internal class CityConfiguration : IEntityTypeConfiguration<City>
    {
        public void Configure(EntityTypeBuilder<City> builder)
        {
            builder.HasKey(c => c.Id);

            builder.Property(c => c.Name) 
                   .IsRequired()
                   .HasMaxLength(200);

            builder.HasOne(c => c.Country)
                   .WithMany(country => country.Cities)
                   .HasForeignKey(c => c.CountryId)
                   .IsRequired()
                   .OnDelete(DeleteBehavior.Restrict);

            builder.ToTable("Cities", schema: "Geography");
            builder.HasData(GetCities());

        }
        private List<City> GetCities()
        {
            return new List<City>
            {
                // United States (CountryId = 1)
                new City { Id = 1, Name = "New York", CountryId = 1 },
                new City { Id = 2, Name = "Los Angeles", CountryId = 1 },
                new City { Id = 3, Name = "Chicago", CountryId = 1 },
                new City { Id = 4, Name = "Houston", CountryId = 1 },
                new City { Id = 5, Name = "Phoenix", CountryId = 1 },
                new City { Id = 6, Name = "Philadelphia", CountryId = 1 },
                new City { Id = 7, Name = "San Antonio", CountryId = 1 },
                new City { Id = 8, Name = "San Diego", CountryId = 1 },
                new City { Id = 9, Name = "Dallas", CountryId = 1 },
                new City { Id = 10, Name = "San Jose", CountryId = 1 },

                // Canada (CountryId = 2)
                new City { Id = 11, Name = "Toronto", CountryId = 2 },
                new City { Id = 12, Name = "Vancouver", CountryId = 2 },
                new City { Id = 13, Name = "Montreal", CountryId = 2 },
                new City { Id = 14, Name = "Calgary", CountryId = 2 },
                new City { Id = 15, Name = "Edmonton", CountryId = 2 },
                new City { Id = 16, Name = "Ottawa", CountryId = 2 },
                new City { Id = 17, Name = "Winnipeg", CountryId = 2 },
                new City { Id = 18, Name = "Quebec City", CountryId = 2 },
                new City { Id = 19, Name = "Hamilton", CountryId = 2 },
                new City { Id = 20, Name = "Victoria", CountryId = 2 },

                // Mexico (CountryId = 3)
                new City { Id = 21, Name = "Mexico City", CountryId = 3 },
                new City { Id = 22, Name = "Guadalajara", CountryId = 3 },
                new City { Id = 23, Name = "Monterrey", CountryId = 3 },
                new City { Id = 24, Name = "Puebla", CountryId = 3 },
                new City { Id = 25, Name = "Tijuana", CountryId = 3 },
                new City { Id = 26, Name = "Leon", CountryId = 3 },
                new City { Id = 27, Name = "Juarez", CountryId = 3 },
                new City { Id = 28, Name = "Merida", CountryId = 3 },
                new City { Id = 29, Name = "Queretaro", CountryId = 3 },
                new City { Id = 30, Name = "Cancun", CountryId = 3 },

                // Brazil (CountryId = 4)
                new City { Id = 31, Name = "Sao Paulo", CountryId = 4 },
                new City { Id = 32, Name = "Rio de Janeiro", CountryId = 4 },
                new City { Id = 33, Name = "Brasilia", CountryId = 4 },
                new City { Id = 34, Name = "Salvador", CountryId = 4 },
                new City { Id = 35, Name = "Fortaleza", CountryId = 4 },
                new City { Id = 36, Name = "Belo Horizonte", CountryId = 4 },
                new City { Id = 37, Name = "Manaus", CountryId = 4 },
                new City { Id = 38, Name = "Curitiba", CountryId = 4 },
                new City { Id = 39, Name = "Recife", CountryId = 4 },
                new City { Id = 40, Name = "Porto Alegre", CountryId = 4 },

                // Argentina (CountryId = 5)
                new City { Id = 41, Name = "Buenos Aires", CountryId = 5 },
                new City { Id = 42, Name = "Cordoba", CountryId = 5 },
                new City { Id = 43, Name = "Rosario", CountryId = 5 },
                new City { Id = 44, Name = "Mendoza", CountryId = 5 },
                new City { Id = 45, Name = "La Plata", CountryId = 5 },
                new City { Id = 46, Name = "San Miguel de Tucuman", CountryId = 5 },
                new City { Id = 47, Name = "Mar del Plata", CountryId = 5 },
                new City { Id = 48, Name = "Salta", CountryId = 5 },
                new City { Id = 49, Name = "Santa Fe", CountryId = 5 },
                new City { Id = 50, Name = "Neuquen", CountryId = 5 },

                // United Kingdom (CountryId = 6)
                new City { Id = 51, Name = "London", CountryId = 6 },
                new City { Id = 52, Name = "Manchester", CountryId = 6 },
                new City { Id = 53, Name = "Birmingham", CountryId = 6 },
                new City { Id = 54, Name = "Liverpool", CountryId = 6 },
                new City { Id = 55, Name = "Glasgow", CountryId = 6 },
                new City { Id = 56, Name = "Edinburgh", CountryId = 6 },
                new City { Id = 57, Name = "Bristol", CountryId = 6 },
                new City { Id = 58, Name = "Leeds", CountryId = 6 },
                new City { Id = 59, Name = "Cardiff", CountryId = 6 },
                new City { Id = 60, Name = "Newcastle", CountryId = 6 },

                // France (CountryId = 7)
                new City { Id = 61, Name = "Paris", CountryId = 7 },
                new City { Id = 62, Name = "Lyon", CountryId = 7 },
                new City { Id = 63, Name = "Marseille", CountryId = 7 },
                new City { Id = 64, Name = "Toulouse", CountryId = 7 },
                new City { Id = 65, Name = "Nice", CountryId = 7 },
                new City { Id = 66, Name = "Nantes", CountryId = 7 },
                new City { Id = 67, Name = "Strasbourg", CountryId = 7 },
                new City { Id = 68, Name = "Bordeaux", CountryId = 7 },
                new City { Id = 69, Name = "Lille", CountryId = 7 },
                new City { Id = 70, Name = "Rennes", CountryId = 7 },

                // Germany (CountryId = 8)
                new City { Id = 71, Name = "Berlin", CountryId = 8 },
                new City { Id = 72, Name = "Hamburg", CountryId = 8 },
                new City { Id = 73, Name = "Mun him", CountryId = 8 },
                new City { Id = 74, Name = "Cologne", CountryId = 8 },
                new City { Id = 75, Name = "Frankfurt", CountryId = 8 },
                new City { Id = 76, Name = "Stuttgart", CountryId = 8 },
                new City { Id = 77, Name = "Dusseldorf", CountryId = 8 },
                new City { Id = 78, Name = "Dortmund", CountryId = 8 },
                new City { Id = 79, Name = "Leipzig", CountryId = 8 },
                new City { Id = 80, Name = "Bremen", CountryId = 8 },

                // Italy (CountryId = 9)
                new City { Id = 81, Name = "Rome", CountryId = 9 },
                new City { Id = 82, Name = "Milan", CountryId = 9 },
                new City { Id = 83, Name = "Naples", CountryId = 9 },
                new City { Id = 84, Name = "Turin", CountryId = 9 },
                new City { Id = 85, Name = "Palermo", CountryId = 9 },
                new City { Id = 86, Name = "Genoa", CountryId = 9 },
                new City { Id = 87, Name = "Bologna", CountryId = 9 },
                new City { Id = 88, Name = "Florence", CountryId = 9 },
                new City { Id = 89, Name = "Bari", CountryId = 9 },
                new City { Id = 90, Name = "Venice", CountryId = 9 },

                // Spain (CountryId = 10)
                new City { Id = 91, Name = "Madrid", CountryId = 10 },
                new City { Id = 92, Name = "Barcelona", CountryId = 10 },
                new City { Id = 93, Name = "Valencia", CountryId = 10 },
                new City { Id = 94, Name = "Seville", CountryId = 10 },
                new City { Id = 95, Name = "Zaragoza", CountryId = 10 },
                new City { Id = 96, Name = "Malaga", CountryId = 10 },
                new City { Id = 97, Name = "Bilbao", CountryId = 10 },
                new City { Id = 98, Name = "Alicante", CountryId = 10 },
                new City { Id = 99, Name = "Cordoba", CountryId = 10 },
                new City { Id = 100, Name = "Valladolid", CountryId = 10 },

                // China (CountryId = 11)
                new City { Id = 101, Name = "Shanghai", CountryId = 11 },
                new City { Id = 102, Name = "Beijing", CountryId = 11 },
                new City { Id = 103, Name = "Guangzhou", CountryId = 11 },
                new City { Id = 104, Name = "Shenzhen", CountryId = 11 },
                new City { Id = 105, Name = "Chengdu", CountryId = 11 },
                new City { Id = 106, Name = "Chongqing", CountryId = 11 },
                new City { Id = 107, Name = "Tianjin", CountryId = 11 },
                new City { Id = 108, Name = "Wuhan", CountryId = 11 },
                new City { Id = 109, Name = "Xi'an", CountryId = 11 },
                new City { Id = 110, Name = "Hangzhou", CountryId = 11 },

                // Japan (CountryId = 12)
                new City { Id = 111, Name = "Tokyo", CountryId = 12 },
                new City { Id = 112, Name = "Osaka", CountryId = 12 },
                new City { Id = 113, Name = "Nagoya", CountryId = 12 },
                new City { Id = 114, Name = "Sapporo", CountryId = 12 },
                new City { Id = 115, Name = "Fukuoka", CountryId = 12 },
                new City { Id = 116, Name = "Kyoto", CountryId = 12 },
                new City { Id = 117, Name = "Hiroshima", CountryId = 12 },
                new City { Id = 118, Name = "Sendai", CountryId = 12 },
                new City { Id = 119, Name = "Kobe", CountryId = 12 },
                new City { Id = 120, Name = "Yokohama", CountryId = 12 },

                // India (CountryId = 13)
                new City { Id = 121, Name = "Mumbai", CountryId = 13 },
                new City { Id = 122, Name = "Delhi", CountryId = 13 },
                new City { Id = 123, Name = "Bangalore", CountryId = 13 },
                new City { Id = 124, Name = "Hyderabad", CountryId = 13 },
                new City { Id = 125, Name = "Ahmedabad", CountryId = 13 },
                new City { Id = 126, Name = "Chennai", CountryId = 13 },
                new City { Id = 127, Name = "Kolkata", CountryId = 13 },
                new City { Id = 128, Name = "Pune", CountryId = 13 },
                new City { Id = 129, Name = "Jaipur", CountryId = 13 },
                new City { Id = 130, Name = "Lucknow", CountryId = 13 },

                // South Korea (CountryId = 14)
                new City { Id = 131, Name = "Seoul", CountryId = 14 },
                new City { Id = 132, Name = "Busan", CountryId = 14 },
                new City { Id = 133, Name = "Incheon", CountryId = 14 },
                new City { Id = 134, Name = "Daegu", CountryId = 14 },
                new City { Id = 135, Name = "Daejeon", CountryId = 14 },
                new City { Id = 136, Name = "Gwangju", CountryId = 14 },
                new City { Id = 137, Name = "Suwon", CountryId = 14 },
                new City { Id = 138, Name = "Ulsan", CountryId = 14 },
                new City { Id = 139, Name = "Changwon", CountryId = 14 },
                new City { Id = 140, Name = "Jeonju", CountryId = 14 },

                // Indonesia (CountryId = 15)
                new City { Id = 141, Name = "Jakarta", CountryId = 15 },
                new City { Id = 142, Name = "Surabaya", CountryId = 15 },
                new City { Id = 143, Name = "Bandung", CountryId = 15 },
                new City { Id = 144, Name = "Medan", CountryId = 15 },
                new City { Id = 145, Name = "Semarang", CountryId = 15 },
                new City { Id = 146, Name = "Makassar", CountryId = 15 },
                new City { Id = 147, Name = "Palembang", CountryId = 15 },
                new City { Id = 148, Name = "Yogyakarta", CountryId = 15 },
                new City { Id = 149, Name = "Denpasar", CountryId = 15 },
                new City { Id = 150, Name = "Balikpapan", CountryId = 15 },

                // Russia (CountryId = 16)
                new City { Id = 151, Name = "Moscow", CountryId = 16 },
                new City { Id = 152, Name = "Saint Petersburg", CountryId = 16 },
                new City { Id = 153, Name = "Novosibirsk", CountryId = 16 },
                new City { Id = 154, Name = "Yekaterinburg", CountryId = 16 },
                new City { Id = 155, Name = "Kazan", CountryId = 16 },
                new City { Id = 156, Name = "Nizhny Novgorod", CountryId = 16 },
                new City { Id = 157, Name = "Chelyabinsk", CountryId = 16 },
                new City { Id = 158, Name = "Samara", CountryId = 16 },
                new City { Id = 159, Name = "Omsk", CountryId = 16 },
                new City { Id = 160, Name = "Rostov-on-Don", CountryId = 16 },

                // South Africa (CountryId = 17)
                new City { Id = 161, Name = "Johannesburg", CountryId = 17 },
                new City { Id = 162, Name = "Cape Town", CountryId = 17 },
                new City { Id = 163, Name = "Durban", CountryId = 17 },
                new City { Id = 164, Name = "Pretoria", CountryId = 17 },
                new City { Id = 165, Name = "Port Elizabeth", CountryId = 17 },
                new City { Id = 166, Name = "Bloemfontein", CountryId = 17 },
                new City { Id = 167, Name = "East London", CountryId = 17 },
                new City { Id = 168, Name = "Polokwane", CountryId = 17 },
                new City { Id = 169, Name = "Nelspruit", CountryId = 17 },
                new City { Id = 170, Name = "Rustenburg", CountryId = 17 },

                // Egypt (CountryId = 18)
                new City { Id = 171, Name = "Cairo", CountryId = 18 },
                new City { Id = 172, Name = "Alexandria", CountryId = 18 },
                new City { Id = 173, Name = "Giza", CountryId = 18 },
                new City { Id = 174, Name = "Luxor", CountryId = 18 },
                new City { Id = 175, Name = "Aswan", CountryId = 18 },
                new City { Id = 176, Name = "Sharm El Sheikh", CountryId = 18 },
                new City { Id = 177, Name = "Hurghada", CountryId = 18 },
                new City { Id = 178, Name = "Mansoura", CountryId = 18 },
                new City { Id = 179, Name = "Tanta", CountryId = 18 },
                new City { Id = 180, Name = "Suez", CountryId = 18 },

                // Nigeria (CountryId = 19)
                new City { Id = 181, Name = "Lagos", CountryId = 19 },
                new City { Id = 182, Name = "Abuja", CountryId = 19 },
                new City { Id = 183, Name = "Kano", CountryId = 19 },
                new City { Id = 184, Name = "Ibadan", CountryId = 19 },
                new City { Id = 185, Name = "Kaduna", CountryId = 19 },
                new City { Id = 186, Name = "Port Harcourt", CountryId = 19 },
                new City { Id = 187, Name = "Benin City", CountryId = 19 },
                new City { Id = 188, Name = "Maiduguri", CountryId = 19 },
                new City { Id = 189, Name = "Zaria", CountryId = 19 },
                new City { Id = 190, Name = "Jos", CountryId = 19 },

                // Kenya (CountryId = 20)
                new City { Id = 191, Name = "Nairobi", CountryId = 20 },
                new City { Id = 192, Name = "Mombasa", CountryId = 20 },
                new City { Id = 193, Name = "Kisumu", CountryId = 20 },
                new City { Id = 194, Name = "Nakuru", CountryId = 20 },
                new City { Id = 195, Name = "Eldoret", CountryId = 20 },
                new City { Id = 196, Name = "Thika", CountryId = 20 },
                new City { Id = 197, Name = "Malindi", CountryId = 20 },
                new City { Id = 198, Name = "Kitale", CountryId = 20 },
                new City { Id = 199, Name = "Garissa", CountryId = 20 },
                new City { Id = 200, Name = "Kakamega", CountryId = 20 },

                // Australia (CountryId = 21)
                new City { Id = 201, Name = "Sydney", CountryId = 21 },
                new City { Id = 202, Name = "Melbourne", CountryId = 21 },
                new City { Id = 203, Name = "Brisbane", CountryId = 21 },
                new City { Id = 204, Name = "Perth", CountryId = 21 },
                new City { Id = 205, Name = "Adelaide", CountryId = 21 },
                new City { Id = 206, Name = "Canberra", CountryId = 21 },
                new City { Id = 207, Name = "Hobart", CountryId = 21 },
                new City { Id = 208, Name = "Darwin", CountryId = 21 },
                new City { Id = 209, Name = "Gold Coast", CountryId = 21 },
                new City { Id = 210, Name = "Newcastle", CountryId = 21 },

                // New Zealand (CountryId = 22)
                new City { Id = 211, Name = "Auckland", CountryId = 22 },
                new City { Id = 212, Name = "Wellington", CountryId = 22 },
                new City { Id = 213, Name = "Christchurch", CountryId = 22 },
                new City { Id = 214, Name = "Hamilton", CountryId = 22 },
                new City { Id = 215, Name = "Tauranga", CountryId = 22 },
                new City { Id = 216, Name = "Dunedin", CountryId = 22 },
                new City { Id = 217, Name = "Palmerston North", CountryId = 22 },
                new City { Id = 218, Name = "Napier", CountryId = 22 },
                new City { Id = 219, Name = "Nelson", CountryId = 22 },
                new City { Id = 220, Name = "Rotorua", CountryId = 22 },

                // Saudi Arabia (CountryId = 23)
                new City { Id = 221, Name = "Riyadh", CountryId = 23 },
                new City { Id = 222, Name = "Jeddah", CountryId = 23 },
                new City { Id = 223, Name = "Mecca", CountryId = 23 },
                new City { Id = 224, Name = "Medina", CountryId = 23 },
                new City { Id = 225, Name = "Dammam", CountryId = 23 },
                new City { Id = 226, Name = "Khobar", CountryId = 23 },
                new City { Id = 227, Name = "Taif", CountryId = 23 },
                new City { Id = 228, Name = "Abha", CountryId = 23 },
                new City { Id = 229, Name = "Tabuk", CountryId = 23 },
                new City { Id = 230, Name = "Hail", CountryId = 23 },

                // Turkey (CountryId = 24)
                new City { Id = 231, Name = "Istanbul", CountryId = 24 },
                new City { Id = 232, Name = "Ankara", CountryId = 24 },
                new City { Id = 233, Name = "Izmir", CountryId = 24 },
                new City { Id = 234, Name = "Bursa", CountryId = 24 },
                new City { Id = 235, Name = "Adana", CountryId = 24 },
                new City { Id = 236, Name = "Antalya", CountryId = 24 },
                new City { Id = 237, Name = "Konya", CountryId = 24 },
                new City { Id = 238, Name = "Gaziantep", CountryId = 24 },
                new City { Id = 239, Name = "Sanliurfa", CountryId = 24 },
                new City { Id = 240, Name = "Mersin", CountryId = 24 },

                // Pakistan (CountryId = 25)
                new City { Id = 241, Name = "Karachi", CountryId = 25 },
                new City { Id = 242, Name = "Lahore", CountryId = 25 },
                new City { Id = 243, Name = "Faisalabad", CountryId = 25 },
                new City { Id = 244, Name = "Rawalpindi", CountryId = 25 },
                new City { Id = 245, Name = "Multan", CountryId = 25 },
                new City { Id = 246, Name = "Hyderabad", CountryId = 25 },
                new City { Id = 247, Name = "Gujranwala", CountryId = 25 },
                new City { Id = 248, Name = "Peshawar", CountryId = 25 },
                new City { Id = 249, Name = "Quetta", CountryId = 25 },
                new City { Id = 250, Name = "Islamabad", CountryId = 25 },

                // Bangladesh (CountryId = 26)
                new City { Id = 251, Name = "Dhaka", CountryId = 26 },
                new City { Id = 252, Name = "Chittagong", CountryId = 26 },
                new City { Id = 253, Name = "Khulna", CountryId = 26 },
                new City { Id = 254, Name = "Rajshahi", CountryId = 26 },
                new City { Id = 255, Name = "Sylhet", CountryId = 26 },
                new City { Id = 256, Name = "Barisal", CountryId = 26 },
                new City { Id = 257, Name = "Rangpur", CountryId = 26 },
                new City { Id = 258, Name = "Comilla  Narayanganj", CountryId = 26 },
                new City { Id = 259, Name = "Mymensingh", CountryId = 26 },
                new City { Id = 260, Name = "Bogra", CountryId = 26 },

                // Vietnam (CountryId = 27)
                new City { Id = 261, Name = "Ho Chi Minh City", CountryId = 27 },
                new City { Id = 262, Name = "Hanoi", CountryId = 27 },
                new City { Id = 263, Name = "Da Nang", CountryId = 27 },
                new City { Id = 264, Name = "Hai Phong", CountryId = 27 },
                new City { Id = 265, Name = "Can Tho", CountryId = 27 },
                new City { Id = 266, Name = "Hue", CountryId = 27 },
                new City { Id = 267, Name = "Nha Trang", CountryId = 27 },
                new City { Id = 268, Name = "Vung Tau", CountryId = 27 },
                new City { Id = 269, Name = "Bien Hoa", CountryId = 27 },
                new City { Id = 270, Name = "Thai Nguyen", CountryId = 27 },

                // Thailand (CountryId = 28)
                new City { Id = 271, Name = "Bangkok", CountryId = 28 },
                new City { Id = 272, Name = "Chiang Mai", CountryId = 28 },
                new City { Id = 273, Name = "Pattaya", CountryId = 28 },
                new City { Id = 274, Name = "Phuket", CountryId = 28 },
                new City { Id = 275, Name = "Hat Yai", CountryId = 28 },
                new City { Id = 276, Name = "Nakhon Ratchasima", CountryId = 28 },
                new City { Id = 277, Name = "Udon Thani", CountryId = 28 },
                new City { Id = 278, Name = "Surat Thani", CountryId = 28 },
                new City { Id = 279, Name = "Khon Kaen", CountryId = 28 },
                new City { Id = 280, Name = "Chiang Rai", CountryId = 28 },

                // Iran (CountryId = 29)
                new City { Id = 281, Name = "Tehran", CountryId = 29 },
                new City { Id = 282, Name = "Mashhad", CountryId = 29 },
                new City { Id = 283, Name = "Isfahan", CountryId = 29 },
                new City { Id = 284, Name = "Shiraz", CountryId = 29 },
                new City { Id = 285, Name = "Tabriz", CountryId = 29 },
                new City { Id = 286, Name = "Karaj", CountryId = 29 },
                new City { Id = 287, Name = "Ahvaz", CountryId = 29 },
                new City { Id = 288, Name = "Qom", CountryId = 29 },
                new City { Id = 289, Name = "Kermanshah", CountryId = 29 },
                new City { Id = 290, Name = "Urmia", CountryId = 29 },

                // Israel (CountryId = 30)
                new City { Id = 291, Name = "Tel Aviv", CountryId = 30 },
                new City { Id = 292, Name = "Jerusalem", CountryId = 30 },
                new City { Id = 293, Name = "Haifa", CountryId = 30 },
                new City { Id = 294, Name = "Rishon LeZion", CountryId = 30 },
                new City { Id = 295, Name = "Petah Tikva", CountryId = 30 },
                new City { Id = 296, Name = "Ashdod", CountryId = 30 },
                new City { Id = 297, Name = "Netanya", CountryId = 30 },
                new City { Id = 298, Name = "Beer Sheva", CountryId = 30 },
                new City { Id = 299, Name = "Holon", CountryId = 30 },
                new City { Id = 300, Name = "Bnei Brak", CountryId = 30 },

                // Malaysia (CountryId = 31)
                new City { Id = 301, Name = "Kuala Lumpur", CountryId = 31 },
                new City { Id = 302, Name = "George Town", CountryId = 31 },
                new City { Id = 303, Name = "Johor Bahru", CountryId = 31 },
                new City { Id = 304, Name = "Ipoh", CountryId = 31 },
                new City { Id = 305, Name = "Shah Alam", CountryId = 31 },
                new City { Id = 306, Name = "Petaling Jaya", CountryId = 31 },
                new City { Id = 307, Name = "Kota Kinabalu", CountryId = 31 },
                new City { Id = 308, Name = "Malacca City", CountryId = 31 },
                new City { Id = 309, Name = "Alor Setar", CountryId = 31 },
                new City { Id = 310, Name = "Kuching", CountryId = 31 },

                // Philippines (CountryId = 32)
                new City { Id = 311, Name = "Quezon City", CountryId = 32 },
                new City { Id = 312, Name = "Manila", CountryId = 32 },
                new City { Id = 313, Name = "Davao City", CountryId = 32 },
                new City { Id = 314, Name = "Cebu City", CountryId = 32 },
                new City { Id = 315, Name = "Zamboanga City", CountryId = 32 },
                new City { Id = 316, Name = "Taguig", CountryId = 32 },
                new City { Id = 317, Name = "Pasig", CountryId = 32 },
                new City { Id = 318, Name = "Cagayan de Oro", CountryId = 32 },
                new City { Id = 319, Name = "Paranaque", CountryId = 32 },
                new City { Id = 320, Name = "Las Pinas", CountryId = 32 },

                // Portugal (CountryId = 33)
                new City { Id = 321, Name = "Lisbon", CountryId = 33 },
                new City { Id = 322, Name = "Porto", CountryId = 33 },
                new City { Id = 323, Name = "Amadora", CountryId = 33 },
                new City { Id = 324, Name = "Braga", CountryId = 33 },
                new City { Id = 325, Name = "Setubal", CountryId = 33 },
                new City { Id = 326, Name = "Coimbra", CountryId = 33 },
                new City { Id = 327, Name = "Queluz", CountryId = 33 },
                new City { Id = 328, Name = "Funchal", CountryId = 33 },
                new City { Id = 329, Name = "Vila Nova de Gaia", CountryId = 33 },
                new City { Id = 330, Name = "Almada", CountryId = 33 },

                // Greece (CountryId = 34)
                new City { Id = 331, Name = "Athens", CountryId = 34 },
                new City { Id = 332, Name = "Thessaloniki", CountryId = 34 },
                new City { Id = 333, Name = "Patras", CountryId = 34 },
                new City { Id = 334, Name = "Heraklion", CountryId = 34 },
                new City { Id = 335, Name = "Larissa", CountryId = 34 },
                new City { Id = 336, Name = "Volos", CountryId = 34 },
                new City { Id = 337, Name = "Ioannina", CountryId = 34 },
                new City { Id = 338, Name = "Chania", CountryId = 34 },
                new City { Id = 339, Name = "Kavala", CountryId = 34 },
                new City { Id = 340, Name = "Kalamata", CountryId = 34 },

                // Netherlands (CountryId = 35)
                new City { Id = 341, Name = "Amsterdam", CountryId = 35 },
                new City { Id = 342, Name = "Rotterdam", CountryId = 35 },
                new City { Id = 343, Name = "The Hague", CountryId = 35 },
                new City { Id = 344, Name = "Utrecht", CountryId = 35 },
                new City { Id = 345, Name = "Eindhoven", CountryId = 35 },
                new City { Id = 346, Name = "Tilburg", CountryId = 35 },
                new City { Id = 347, Name = "Groningen", CountryId = 35 },
                new City { Id = 348, Name = "Almere", CountryId = 35 },
                new City { Id = 349, Name = "Breda", CountryId = 35 },
                new City { Id = 350, Name = "Nijmegen", CountryId = 35 },

                // Sweden (CountryId = 36)
                new City { Id = 351, Name = "Stockholm", CountryId = 36 },
                new City { Id = 352, Name = "Gothenburg", CountryId = 36 },
                new City { Id = 353, Name = "Malmo", CountryId = 36 },
                new City { Id = 354, Name = "Uppsala", CountryId = 36 },
                new City { Id = 355, Name = "Vasteras", CountryId = 36 },
                                new City { Id = 356, Name = "Orebro", CountryId = 36 },
                new City { Id = 357, Name = "Linkoping", CountryId = 36 },
                new City { Id = 358, Name = "Helsingborg", CountryId = 36 },
                new City { Id = 359, Name = "Jonkoping", CountryId = 36 },
                new City { Id = 360, Name = "Norrkoping", CountryId = 36 },

                // Norway (CountryId = 37)
                new City { Id = 361, Name = "Oslo", CountryId = 37 },
                new City { Id = 362, Name = "Bergen", CountryId = 37 },
                new City { Id = 363, Name = "Trondheim", CountryId = 37 },
                new City { Id = 364, Name = "Stavanger", CountryId = 37 },
                new City { Id = 365, Name = "Drammen", CountryId = 37 },
                new City { Id = 366, Name = "Fredrikstad", CountryId = 37 },
                new City { Id = 367, Name = "Kristiansand", CountryId = 37 },
                new City { Id = 368, Name = "Sandnes", CountryId = 37 },
                new City { Id = 369, Name = "Tromsø", CountryId = 37 },
                new City { Id = 370, Name = "Ålesund", CountryId = 37 },

                // Denmark (CountryId = 38)
                new City { Id = 371, Name = "Copenhagen", CountryId = 38 },
                new City { Id = 372, Name = "Aarhus", CountryId = 38 },
                new City { Id = 373, Name = "Odense", CountryId = 38 },
                new City { Id = 374, Name = "Aalborg", CountryId = 38 },
                new City { Id = 375, Name = "Esbjerg", CountryId = 38 },
                new City { Id = 376, Name = "Randers", CountryId = 38 },
                new City { Id = 377, Name = "Kolding", CountryId = 38 },
                new City { Id = 378, Name = "Horsens", CountryId = 38 },
                new City { Id = 379, Name = "Vejle", CountryId = 38 },
                new City { Id = 380, Name = "Roskilde", CountryId = 38 },

                // Switzerland (CountryId = 39)
                new City { Id = 381, Name = "Zurich", CountryId = 39 },
                new City { Id = 382, Name = "Geneva", CountryId = 39 },
                new City { Id = 383, Name = "Basel", CountryId = 39 },
                new City { Id = 384, Name = "Lausanne", CountryId = 39 },
                new City { Id = 385, Name = "Bern", CountryId = 39 },
                new City { Id = 386, Name = "Lucerne", CountryId = 39 },
                new City { Id = 387, Name = "St. Gallen", CountryId = 39 },
                new City { Id = 388, Name = "Lugano", CountryId = 39 },
                new City { Id = 389, Name = "Biel/Bienne", CountryId = 39 },
                new City { Id = 390, Name = "Thun", CountryId = 39 },

                // Poland (CountryId = 40)
                new City { Id = 391, Name = "Warsaw", CountryId = 40 },
                new City { Id = 392, Name = "Krakow", CountryId = 40 },
                new City { Id = 393, Name = "Lodz", CountryId = 40 },
                new City { Id = 394, Name = "Wroclaw", CountryId = 40 },
                new City { Id = 395, Name = "Poznan", CountryId = 40 },
                new City { Id = 396, Name = "Gdansk", CountryId = 40 },
                new City { Id = 397, Name = "Szczecin", CountryId = 40 },
                new City { Id = 398, Name = "Bydgoszcz", CountryId = 40 },
                new City { Id = 399, Name = "Lublin", CountryId = 40 },
                new City { Id = 400, Name = "Katowice", CountryId = 40 },

                // Belgium (CountryId = 41)
                new City { Id = 401, Name = "Brussels", CountryId = 41 },
                new City { Id = 402, Name = "Antwerp", CountryId = 41 },
                new City { Id = 403, Name = "Ghent", CountryId = 41 },
                new City { Id = 404, Name = "Charleroi", CountryId = 41 },
                new City { Id = 405, Name = "Liege", CountryId = 41 },
                new City { Id = 406, Name = "Bruges", CountryId = 41 },
                new City { Id = 407, Name = "Namur", CountryId = 41 },
                new City { Id = 408, Name = "Leuven", CountryId = 41 },
                new City { Id = 409, Name = "Mons", CountryId = 41 },
                new City { Id = 410, Name = "Aalst", CountryId = 41 },

                // Romania (CountryId = 42)
                new City { Id = 411, Name = "Bucharest", CountryId = 42 },
                new City { Id = 412, Name = "Cluj-Napoca", CountryId = 42 },
                new City { Id = 413, Name = "Timisoara", CountryId = 42 },
                new City { Id = 414, Name = "Iasi", CountryId = 42 },
                new City { Id = 415, Name = "Constanta", CountryId = 42 },
                new City { Id = 416, Name = "Craiova", CountryId = 42 },
                new City { Id = 417, Name = "Brasov", CountryId = 42 },
                new City { Id = 418, Name = "Galati", CountryId = 42 },
                new City { Id = 419, Name = "Ploiesti", CountryId = 42 },
                new City { Id = 420, Name = "Oradea", CountryId = 42 },

                // Czech Republic (CountryId = 43)
                new City { Id = 421, Name = "Prague", CountryId = 43 },
                new City { Id = 422, Name = "Brno", CountryId = 43 },
                new City { Id = 423, Name = "Ostrava", CountryId = 43 },
                new City { Id = 424, Name = "Plzen", CountryId = 43 },
                new City { Id = 425, Name = "Liberec", CountryId = 43 },
                new City { Id = 426, Name = "Olomouc", CountryId = 43 },
                new City { Id = 427, Name = "Ceske Budejovice", CountryId = 43 },
                new City { Id = 428, Name = "Hradec Kralove", CountryId = 43 },
                new City { Id = 429, Name = "Usti nad Labem", CountryId = 43 },
                new City { Id = 430, Name = "Pardubice", CountryId = 43 },

                // Hungary (CountryId = 44)
                new City { Id = 431, Name = "Budapest", CountryId = 44 },
                new City { Id = 432, Name = "Debrecen", CountryId = 44 },
                new City { Id = 433, Name = "Szeged", CountryId = 44 },
                new City { Id = 434, Name = "Miskolc", CountryId = 44 },
                new City { Id = 435, Name = "Pecs", CountryId = 44 },
                new City { Id = 436, Name = "Gyor", CountryId = 44 },
                new City { Id = 437, Name = "Nyiregyhaza", CountryId = 44 },
                new City { Id = 438, Name = "Kecskemet", CountryId = 44 },
                new City { Id = 439, Name = "Szekesfehervar", CountryId = 44 },
                new City { Id = 440, Name = "Szombathely", CountryId = 44 },

                // Ukraine (CountryId = 45)
                new City { Id = 441, Name = "Kyiv", CountryId = 45 },
                new City { Id = 442, Name = "Kharkiv", CountryId = 45 },
                new City { Id = 443, Name = "Odesa", CountryId = 45 },
                new City { Id = 444, Name = "Dnipro", CountryId = 45 },
                new City { Id = 445, Name = "Donetsk", CountryId = 45 },
                new City { Id = 446, Name = "Zaporizhzhia", CountryId = 45 },
                new City { Id = 447, Name = "Lviv", CountryId = 45 },
                new City { Id = 448, Name = "Kryvyi Rih", CountryId = 45 },
                new City { Id = 449, Name = "Mykolaiv", CountryId = 45 },
                new City { Id = 450, Name = "Mariupol", CountryId = 45 },

                // Colombia (CountryId = 46)
                new City { Id = 451, Name = "Bogota", CountryId = 46 },
                new City { Id = 452, Name = "Medellin", CountryId = 46 },
                new City { Id = 453, Name = "Cali", CountryId = 46 },
                new City { Id = 454, Name = "Barranquilla", CountryId = 46 },
                new City { Id = 455, Name = "Cartagena", CountryId = 46 },
                new City { Id = 456, Name = "Bucaramanga", CountryId = 46 },
                new City { Id = 457, Name = "Cucuta", CountryId = 46 },
                new City { Id = 458, Name = "Pereira", CountryId = 46 },
                new City { Id = 459, Name = "Manizales", CountryId = 46 },
                new City { Id = 460, Name = "Ibague", CountryId = 46 },

                // Chile (CountryId = 47)
                new City { Id = 461, Name = "Santiago", CountryId = 47 },
                new City { Id = 462, Name = "Valparaiso", CountryId = 47 },
                new City { Id = 463, Name = "Concepcion", CountryId = 47 },
                new City { Id = 464, Name = "Antofagasta", CountryId = 47 },
                new City { Id = 465, Name = "Vina del Mar", CountryId = 47 },
                new City { Id = 466, Name = "Temuco", CountryId = 47 },
                new City { Id = 467, Name = "Rancagua", CountryId = 47 },
                new City { Id = 468, Name = "Talca", CountryId = 47 },
                new City { Id = 469, Name = "Arica", CountryId = 47 },
                new City { Id = 470, Name = "Puerto Montt", CountryId = 47 },

                // Peru (CountryId = 48)
                new City { Id = 471, Name = "Lima", CountryId = 48 },
                new City { Id = 472, Name = "Arequipa", CountryId = 48 },
                new City { Id = 473, Name = "Trujillo", CountryId = 48 },
                new City { Id = 474, Name = "Chiclayo", CountryId = 48 },
                new City { Id = 475, Name = "Piura", CountryId = 48 },
                new City { Id = 476, Name = "Cusco", CountryId = 48 },
                new City { Id = 477, Name = "Iquitos", CountryId = 48 },
                new City { Id = 478, Name = "Huancayo", CountryId = 48 },
                new City { Id = 479, Name = "Chimbote", CountryId = 48 },
                new City { Id = 480, Name = "Pucallpa", CountryId = 48 },

                // Venezuela (CountryId = 49)
                new City { Id = 481, Name = "Caracas", CountryId = 49 },
                new City { Id = 482, Name = "Maracaibo", CountryId = 49 },
                new City { Id = 483, Name = "Valencia", CountryId = 49 },
                new City { Id = 484, Name = "Barquisimeto", CountryId = 49 },
                new City { Id = 485, Name = "Maracay", CountryId = 49 },
                new City { Id = 486, Name = "Ciudad Guayana", CountryId = 49 },
                new City { Id = 487, Name = "Barcelona", CountryId = 49 },
                new City { Id = 488, Name = "Maturin", CountryId = 49 },
                new City { Id = 489, Name = "Cumana", CountryId = 49 },
                new City { Id = 490, Name = "Puerto La Cruz", CountryId = 49 },

                // Ecuador (CountryId = 50)
                new City { Id = 491, Name = "Quito", CountryId = 50 },
                new City { Id = 492, Name = "Guayaquil", CountryId = 50 },
                new City { Id = 493, Name = "Cuenca", CountryId = 50 },
                new City { Id = 494, Name = "Santo Domingo", CountryId = 50 },
                new City { Id = 495, Name = "Machala", CountryId = 50 },
                new City { Id = 496, Name = "Ambato", CountryId = 50 },
                new City { Id = 497, Name = "Portoviejo", CountryId = 50 },
                new City { Id = 498, Name = "Loja", CountryId = 50 },
                new City { Id = 499, Name = "Esmeraldas", CountryId = 50 },
                new City { Id = 500, Name = "Ibarra", CountryId = 50 },

                // United Arab Emirates (CountryId = 51)
                new City { Id = 501, Name = "Dubai", CountryId = 51 },
                new City { Id = 502, Name = "Abu Dhabi", CountryId = 51 },
                new City { Id = 503, Name = "Sharjah", CountryId = 51 },
                new City { Id = 504, Name = "Al Ain", CountryId = 51 },
                new City { Id = 505, Name = "Ajman", CountryId = 51 },
                new City { Id = 506, Name = "Ras Al Khaimah", CountryId = 51 },
                new City { Id = 507, Name = "Fujairah", CountryId = 51 },
                new City { Id = 508, Name = "Umm Al Quwain", CountryId = 51 },
                new City { Id = 509, Name = "Khor Fakkan", CountryId = 51 },
                new City { Id = 510, Name = "Dibba Al-Fujairah", CountryId = 51 },

                // Singapore (CountryId = 52)
                new City { Id = 511, Name = "Singapore", CountryId = 52 },
                new City { Id = 512, Name = "Woodlands", CountryId = 52 },
                new City { Id = 513, Name = "Jurong West", CountryId = 52 },
                new City { Id = 514, Name = "Tampines", CountryId = 52 },
                new City { Id = 515, Name = "Sengkang", CountryId = 52 },
                new City { Id = 516, Name = "Bedok", CountryId = 52 },
                new City { Id = 517, Name = "Yishun", CountryId = 52 },
                new City { Id = 518, Name = "Hougang", CountryId = 52 },
                new City { Id = 519, Name = "Ang Mo Kio", CountryId = 52 },
                new City { Id = 520, Name = "Punggol", CountryId = 52 },

                // Qatar (CountryId = 53)
                new City { Id = 521, Name = "Doha", CountryId = 53 },
                new City { Id = 522, Name = "Al Rayyan", CountryId = 53 },
                new City { Id = 523, Name = "Al Wakrah", CountryId = 53 },
                new City { Id = 524, Name = "Al Khor", CountryId = 53 },
                new City { Id = 525, Name = "Umm Salal", CountryId = 53 },
                new City { Id = 526, Name = "Dukhan", CountryId = 53 },
                new City { Id = 527, Name = "Mesaieed", CountryId = 53 },
                new City { Id = 528, Name = "Madinat ash Shamal", CountryId = 53 },
                new City { Id = 529, Name = "Al Shamal", CountryId = 53 },
                new City { Id = 530, Name = "Al Ghuwariyah", CountryId = 53 },

                // South Sudan (CountryId = 54)
                new City { Id = 531, Name = "Juba", CountryId = 54 },
                new City { Id = 532, Name = "Wau", CountryId = 54 },
                new City { Id = 533, Name = "Malakal", CountryId = 54 },
                new City { Id = 534, Name = "Yei", CountryId = 54 },
                new City { Id = 535, Name = "Bor", CountryId = 54 },
                new City { Id = 536, Name = "Rumbek", CountryId = 54 },
                new City { Id = 537, Name = "Torit", CountryId = 54 },
                new City { Id = 538, Name = "Yambio", CountryId = 54 },
                new City { Id = 539, Name = "Aweil", CountryId = 54 },
                new City { Id = 540, Name = "Nimule", CountryId = 54 },

                // Myanmar (CountryId = 55)
                new City { Id = 541, Name = "Yangon", CountryId = 55 },
                new City { Id = 542, Name = "Mandalay", CountryId = 55 },
                new City { Id = 543, Name = "Naypyidaw", CountryId = 55 },
                new City { Id = 544, Name = "Mawlamyine", CountryId = 55 },
                new City { Id = 545, Name = "Bago", CountryId = 55 },
                new City { Id = 546, Name = "Pathein", CountryId = 55 },
                new City { Id = 547, Name = "Monywa", CountryId = 55 },
                new City { Id = 548, Name = "Sittwe", CountryId = 55 },
                new City { Id = 549, Name = "Myitkyina", CountryId = 55 },
                new City { Id = 550, Name = "Taunggyi", CountryId = 55 },

                // Kazakhstan (CountryId = 56)
                new City { Id = 551, Name = "Astana", CountryId = 56 },
                new City { Id = 552, Name = "Almaty", CountryId = 56 },
                new City { Id = 553, Name = "Shymkent", CountryId = 56 },
                new City { Id = 554, Name = "Karaganda", CountryId = 56 },
                new City { Id = 555, Name = "Aktobe", CountryId = 56 },
                new City { Id = 556, Name = "Taraz", CountryId = 56 },
                new City { Id = 557, Name = "Pavlodar", CountryId = 56 },
                new City { Id = 558, Name = "Ust-Kamenogorsk", CountryId = 56 },
                new City { Id = 559, Name = "Semey", CountryId = 56 },
                new City { Id = 560, Name = "Kostanay", CountryId = 56 },

                // Algeria (CountryId = 57)
                new City { Id = 561, Name = "Algiers", CountryId = 57 },
                new City { Id = 562, Name = "Oran", CountryId = 57 },
                new City { Id = 563, Name = "Constantine", CountryId = 57 },
                new City { Id = 564, Name = "Annaba", CountryId = 57 },
                new City { Id = 565, Name = "Blida", CountryId = 57 },
                new City { Id = 566, Name = "Batna", CountryId = 57 },
                new City { Id = 567, Name = "Djelfa", CountryId = 57 },
                new City { Id = 568, Name = "Sétif", CountryId = 57 },
                new City { Id = 569, Name = "Sidi Bel Abbes", CountryId = 57 },
                new City { Id = 570, Name = "Biskra", CountryId = 57 },

                // Morocco (CountryId = 58)
                new City { Id = 571, Name = "Casablanca", CountryId = 58 },
                new City { Id = 572, Name = "Rabat", CountryId = 58 },
                new City { Id = 573, Name = "Fes", CountryId = 58 },
                new City { Id = 574, Name = "Marrakesh", CountryId = 58 },
                new City { Id = 575, Name = "Tangier", CountryId = 58 },
                new City { Id = 576, Name = "Agadir", CountryId = 58 },
                new City { Id = 577, Name = "Meknes", CountryId = 58 },
                new City { Id = 578, Name = "Oujda", CountryId = 58 },
                new City { Id = 579, Name = "Kenitra", CountryId = 58 },
                new City { Id = 580, Name = "Tetouan", CountryId = 58 },

                // Tunisia (CountryId = 59)
                new City { Id = 581, Name = "Tunis", CountryId = 59 },
                new City { Id = 582, Name = "Sfax", CountryId = 59 },
                new City { Id = 583, Name = "Sousse", CountryId = 59 },
                new City { Id = 584, Name = "Kairouan", CountryId = 59 },
                new City { Id = 585, Name = "Bizerte", CountryId = 59 },
                new City { Id = 586, Name = "Gabes", CountryId = 59 },
                new City { Id = 587, Name = "Ariana", CountryId = 59 },
                new City { Id = 588, Name = "Gafsa", CountryId = 59 },
                new City { Id = 589, Name = "Monastir", CountryId = 59 },
                new City { Id = 590, Name = "Ben Arous", CountryId = 59 },

                // Lebanon (CountryId = 60)
                new City { Id = 591, Name = "Beirut", CountryId = 60 },
                new City { Id = 592, Name = "Tripoli", CountryId = 60 },
                new City { Id = 593, Name = "Sidon", CountryId = 60 },
                new City { Id = 594, Name = "Tyre", CountryId = 60 },
                new City { Id = 595, Name = "Jounieh", CountryId = 60 },
                new City { Id = 596, Name = "Zahle", CountryId = 60 },
                                new City { Id = 597, Name = "Baalbek", CountryId = 60 },
                new City { Id = 598, Name = "Byblos", CountryId = 60 },
                new City { Id = 599, Name = "Nabatieh", CountryId = 60 },
                new City { Id = 600, Name = "Batroun", CountryId = 60 },

                // Jordan (CountryId = 61)
                new City { Id = 601, Name = "Amman", CountryId = 61 },
                new City { Id = 602, Name = "Zarqa", CountryId = 61 },
                new City { Id = 603, Name = "Irbid", CountryId = 61 },
                new City { Id = 604, Name = "Aqaba", CountryId = 61 },
                new City { Id = 605, Name = "Madaba", CountryId = 61 },
                new City { Id = 606, Name = "Salt", CountryId = 61 },
                new City { Id = 607, Name = "Jerash", CountryId = 61 },
                new City { Id = 608, Name = "Karak", CountryId = 61 },
                new City { Id = 609, Name = "Mafraq", CountryId = 61 },
                new City { Id = 610, Name = "Tafilah", CountryId = 61 },

                // Sri Lanka (CountryId = 62)
                new City { Id = 611, Name = "Colombo", CountryId = 62 },
                new City { Id = 612, Name = "Kandy", CountryId = 62 },
                new City { Id = 613, Name = "Galle", CountryId = 62 },
                new City { Id = 614, Name = "Jaffna", CountryId = 62 },
                new City { Id = 615, Name = "Negombo", CountryId = 62 },
                new City { Id = 616, Name = "Ratnapura", CountryId = 62 },
                new City { Id = 617, Name = "Batticaloa", CountryId = 62 },
                new City { Id = 618, Name = "Trincomalee", CountryId = 62 },
                new City { Id = 619, Name = "Anuradhapura", CountryId = 62 },
                new City { Id = 620, Name = "Matara", CountryId = 62 },

                // Nepal (CountryId = 63)
                new City { Id = 621, Name = "Kathmandu", CountryId = 63 },
                new City { Id = 622, Name = "Pokhara", CountryId = 63 },
                new City { Id = 623, Name = "Lalitpur", CountryId = 63 },
                new City { Id = 624, Name = "Biratnagar", CountryId = 63 },
                new City { Id = 625, Name = "Bharatpur", CountryId = 63 },
                new City { Id = 626, Name = "Birgunj", CountryId = 63 },
                new City { Id = 627, Name = "Hetauda", CountryId = 63 },
                new City { Id = 628, Name = "Nepalgunj", CountryId = 63 },
                new City { Id = 629, Name = "Dhangadhi", CountryId = 63 },
                new City { Id = 630, Name = "Janakpur", CountryId = 63 },

                // Mongolia (CountryId = 64)
                new City { Id = 631, Name = "Ulaanbaatar", CountryId = 64 },
                new City { Id = 632, Name = "Erdenet", CountryId = 64 },
                new City { Id = 633, Name = "Darkhan", CountryId = 64 },
                new City { Id = 634, Name = "Choibalsan", CountryId = 64 },
                new City { Id = 635, Name = "Mörön", CountryId = 64 },
                new City { Id = 636, Name = "Khovd", CountryId = 64 },
                new City { Id = 637, Name = "Ölgii", CountryId = 64 },
                new City { Id = 638, Name = "Ulaangom", CountryId = 64 },
                new City { Id = 639, Name = "Sainshand", CountryId = 64 },
                new City { Id = 640, Name = "Tsetserleg", CountryId = 64 },

                // Uzbekistan (CountryId = 65)
                new City { Id = 641, Name = "Tashkent", CountryId = 65 },
                new City { Id = 642, Name = "Samarkand", CountryId = 65 },
                new City { Id = 643, Name = "Namangan", CountryId = 65 },
                new City { Id = 644, Name = "Andijan", CountryId = 65 },
                new City { Id = 645, Name = "Bukhara", CountryId = 65 },
                new City { Id = 646, Name = "Fergana", CountryId = 65 },
                new City { Id = 647, Name = "Jizzakh", CountryId = 65 },
                new City { Id = 648, Name = "Urgench", CountryId = 65 },
                new City { Id = 649, Name = "Nukus", CountryId = 65 },
                new City { Id = 650, Name = "Qarshi", CountryId = 65 },

                // Turkmenistan (CountryId = 66)
                new City { Id = 651, Name = "Ashgabat", CountryId = 66 },
                new City { Id = 652, Name = "Türkmenabat", CountryId = 66 },
                new City { Id = 653, Name = "Daşoguz", CountryId = 66 },
                new City { Id = 654, Name = "Mary", CountryId = 66 },
                new City { Id = 655, Name = "Balkanabat", CountryId = 66 },
                new City { Id = 656, Name = "Bayramaly", CountryId = 66 },
                new City { Id = 657, Name = "Türkmenbaşy", CountryId = 66 },
                new City { Id = 658, Name = "Tejen", CountryId = 66 },
                new City { Id = 659, Name = "Kerki", CountryId = 66 },
                new City { Id = 660, Name = "Seydi", CountryId = 66 },

                // Bolivia (CountryId = 67)
                new City { Id = 661, Name = "La Paz", CountryId = 67 },
                new City { Id = 662, Name = "Santa Cruz de la Sierra", CountryId = 67 },
                new City { Id = 663, Name = "Cochabamba", CountryId = 67 },
                new City { Id = 664, Name = "Sucre", CountryId = 67 },
                new City { Id = 665, Name = "Oruro", CountryId = 67 },
                new City { Id = 666, Name = "Potosí", CountryId = 67 },
                new City { Id = 667, Name = "Tarija", CountryId = 67 },
                new City { Id = 668, Name = "Trinidad", CountryId = 67 },
                new City { Id = 669, Name = "Cobija", CountryId = 67 },
                new City { Id = 670, Name = "Riberalta", CountryId = 67 },

                // Paraguay (CountryId = 68)
                new City { Id = 671, Name = "Asunción", CountryId = 68 },
                new City { Id = 672, Name = "Ciudad del Este", CountryId = 68 },
                new City { Id = 673, Name = "Encarnación", CountryId = 68 },
                new City { Id = 674, Name = "Luque", CountryId = 68 },
                new City { Id = 675, Name = "San Lorenzo", CountryId = 68 },
                new City { Id = 676, Name = "Capiatá", CountryId = 68 },
                new City { Id = 677, Name = "Lambaré", CountryId = 68 },
                new City { Id = 678, Name = "Fernando de la Mora", CountryId = 68 },
                new City { Id = 679, Name = "Pedro Juan Caballero", CountryId = 68 },
                new City { Id = 680, Name = "Coronel Oviedo", CountryId = 68 },

                // Uruguay (CountryId = 69)
                new City { Id = 681, Name = "Montevideo", CountryId = 69 },
                new City { Id = 682, Name = "Salto", CountryId = 69 },
                new City { Id = 683, Name = "Paysandú", CountryId = 69 },
                new City { Id = 684, Name = "Maldonado", CountryId = 69 },
                new City { Id = 685, Name = "Rivera", CountryId = 69 },
                new City { Id = 686, Name = "Las Piedras", CountryId = 69 },
                new City { Id = 687, Name = "Tacuarembó", CountryId = 69 },
                new City { Id = 688, Name = "Mercedes", CountryId = 69 },
                new City { Id = 689, Name = "Artigas", CountryId = 69 },
                new City { Id = 690, Name = "Minas", CountryId = 69 },

                // Costa Rica (CountryId = 70)
                new City { Id = 691, Name = "San José", CountryId = 70 },
                new City { Id = 692, Name = "Alajuela", CountryId = 70 },
                new City { Id = 693, Name = "Cartago", CountryId = 70 },
                new City { Id = 694, Name = "Heredia", CountryId = 70 },
                new City { Id = 695, Name = "Puntarenas", CountryId = 70 },
                new City { Id = 696, Name = "Limón", CountryId = 70 },
                new City { Id = 697, Name = "Liberia", CountryId = 70 },
                new City { Id = 698, Name = "San Isidro de El General", CountryId = 70 },
                new City { Id = 699, Name = "Quesada", CountryId = 70 },
                new City { Id = 700, Name = "Desamparados", CountryId = 70 },

                // Panama (CountryId = 71)
                new City { Id = 701, Name = "Panama City", CountryId = 71 },
                new City { Id = 702, Name = "Colón", CountryId = 71 },
                new City { Id = 703, Name = "David", CountryId = 71 },
                new City { Id = 704, Name = "La Chorrera", CountryId = 71 },
                new City { Id = 705, Name = "Santiago", CountryId = 71 },
                new City { Id = 706, Name = "Chitré", CountryId = 71 },
                new City { Id = 707, Name = "Penonomé", CountryId = 71 },
                new City { Id = 708, Name = "Las Tablas", CountryId = 71 },
                new City { Id = 709, Name = "Bocas del Toro", CountryId = 71 },
                new City { Id = 710, Name = "Aguadulce", CountryId = 71 },

                // Honduras (CountryId = 72)
                new City { Id = 711, Name = "Tegucigalpa", CountryId = 72 },
                new City { Id = 712, Name = "San Pedro Sula", CountryId = 72 },
                new City { Id = 713, Name = "Choloma", CountryId = 72 },
                new City { Id = 714, Name = "La Ceiba", CountryId = 72 },
                new City { Id = 715, Name = "El Progreso", CountryId = 72 },
                new City { Id = 716, Name = "Comayagua", CountryId = 72 },
                new City { Id = 717, Name = "Puerto Cortés", CountryId = 72 },
                new City { Id = 718, Name = "Juticalpa", CountryId = 72 },
                new City { Id = 719, Name = "Siguatepeque", CountryId = 72 },
                new City { Id = 720, Name = "Santa Rosa de Copán", CountryId = 72 },

                // El Salvador (CountryId = 73)
                new City { Id = 721, Name = "San Salvador", CountryId = 73 },
                new City { Id = 722, Name = "Santa Ana", CountryId = 73 },
                new City { Id = 723, Name = "San Miguel", CountryId = 73 },
                new City { Id = 724, Name = "Soyapango", CountryId = 73 },
                new City { Id = 725, Name = "Mejicanos", CountryId = 73 },
                new City { Id = 726, Name = "Apopa", CountryId = 73 },
                new City { Id = 727, Name = "Santa Tecla", CountryId = 73 },
                new City { Id = 728, Name = "Delgado", CountryId = 73 },
                new City { Id = 729, Name = "Sonsonate", CountryId = 73 },
                new City { Id = 730, Name = "Usulután", CountryId = 73 },

                // Guatemala (CountryId = 74)
                new City { Id = 731, Name = "Guatemala City", CountryId = 74 },
                new City { Id = 732, Name = "Quetzaltenango", CountryId = 74 },
                new City { Id = 733, Name = "Mixco", CountryId = 74 },
                new City { Id = 734, Name = "Villa Nueva", CountryId = 74 },
                new City { Id = 735, Name = "Escuintla", CountryId = 74 },
                new City { Id = 736, Name = "San Juan Sacatepéquez", CountryId = 74 },
                new City { Id = 737, Name = "Chimaltenango", CountryId = 74 },
                new City { Id = 738, Name = "Huehuetenango", CountryId = 74 },
                new City { Id = 739, Name = "Coban", CountryId = 74 },
                new City { Id = 740, Name = "Chichicastenango", CountryId = 74 },

                // Dominican Republic (CountryId = 75)
                new City { Id = 741, Name = "Santo Domingo", CountryId = 75 },
                new City { Id = 742, Name = "Santiago de los Caballeros", CountryId = 75 },
                new City { Id = 743, Name = "La Romana", CountryId = 75 },
                new City { Id = 744, Name = "San Pedro de Macorís", CountryId = 75 },
                new City { Id = 745, Name = "San Francisco de Macorís", CountryId = 75 },
                new City { Id = 746, Name = "Puerto Plata", CountryId = 75 },
                new City { Id = 747, Name = "La Vega", CountryId = 75 },
                new City { Id = 748, Name = "Baní", CountryId = 75 },
                new City { Id = 749, Name = "San Cristóbal", CountryId = 75 },
                new City { Id = 750, Name = "Barahona", CountryId = 75 },

                // Kuwait (CountryId = 76)
                new City { Id = 751, Name = "Kuwait City", CountryId = 76 },
                new City { Id = 752, Name = "Hawalli", CountryId = 76 },
                new City { Id = 753, Name = "Al Farwaniyah", CountryId = 76 },
                new City { Id = 754, Name = "Mubarak Al-Kabeer", CountryId = 76 },
                new City { Id = 755, Name = "Al Ahmadi", CountryId = 76 },
                new City { Id = 756, Name = "Jahra", CountryId = 76 },
                new City { Id = 757, Name = "Fintas", CountryId = 76 },
                new City { Id = 758, Name = "Salmiya", CountryId = 76 },
                new City { Id = 759, Name = "Sabah Al-Salem", CountryId = 76 },
                new City { Id = 760, Name = "Mangaf", CountryId = 76 },

                // Bahrain (CountryId = 77)
                new City { Id = 761, Name = "Manama", CountryId = 77 },
                new City { Id = 762, Name = "Riffa", CountryId = 77 },
                new City { Id = 763, Name = "Muharraq", CountryId = 77 },
                new City { Id = 764, Name = "Hamad Town", CountryId = 77 },
                new City { Id = 765, Name = "A'ali", CountryId = 77 },
                new City { Id = 766, Name = "Isa Town", CountryId = 77 },
                new City { Id = 767, Name = "Sitra", CountryId = 77 },
                new City { Id = 768, Name = "Budaiya", CountryId = 77 },
                new City { Id = 769, Name = "Jidhafs", CountryId = 77 },
                new City { Id = 770, Name = "Seef", CountryId = 77 },

                // Oman (CountryId = 78)
                new City { Id = 771, Name = "Muscat", CountryId = 78 },
                new City { Id = 772, Name = "Salalah", CountryId = 78 },
                new City { Id = 773, Name = "Sohar", CountryId = 78 },
                new City { Id = 774, Name = "Nizwa", CountryId = 78 },
                new City { Id = 775, Name = "Sur", CountryId = 78 },
                new City { Id = 776, Name = "Ibri", CountryId = 78 },
                new City { Id = 777, Name = "Rustaq", CountryId = 78 },
                new City { Id = 778, Name = "Barka", CountryId = 78 },
                new City { Id = 779, Name = "Khasab", CountryId = 78 },
                new City { Id = 780, Name = "Al Buraimi", CountryId = 78 },

                // Iraq (CountryId = 79)
                new City { Id = 781, Name = "Baghdad", CountryId = 79 },
                new City { Id = 782, Name = "Basra", CountryId = 79 },
                new City { Id = 783, Name = "Mosul", CountryId = 79 },
                new City { Id = 784, Name = "Erbil", CountryId = 79 },
                new City { Id = 785, Name = "Najaf", CountryId = 79 },
                new City { Id = 786, Name = "Karbala", CountryId = 79 },
                new City { Id = 787, Name = "Sulaymaniyah", CountryId = 79 },
                new City { Id = 788, Name = "Kirkuk", CountryId = 79 },
                new City { Id = 789, Name = "Hilla", CountryId = 79 },
                new City { Id = 790, Name = "Diwaniyah", CountryId = 79 },

                // Syria (CountryId = 80)
                new City { Id = 791, Name = "Damascus", CountryId = 80 },
                new City { Id = 792, Name = "Aleppo", CountryId = 80 },
                new City { Id = 793, Name = "Homs", CountryId = 80 },
                new City { Id = 794, Name = "Latakia", CountryId = 80 },
                new City { Id = 795, Name = "Hama", CountryId = 80 },
                new City { Id = 796, Name = "Deir ez-Zor", CountryId = 80 },
                new City { Id = 797, Name = "Raqqa", CountryId = 80 },
                new City { Id = 798, Name = "Tartus", CountryId = 80 },
                new City { Id = 799, Name = "Daraa", CountryId = 80 },
                new City { Id = 800, Name = "Idlib", CountryId = 80 },

                // Yemen (CountryId = 81)
                new City { Id = 801, Name = "Sana'a", CountryId = 81 },
                new City { Id = 802, Name = "Aden", CountryId = 81 },
                new City { Id = 803, Name = "Taiz", CountryId = 81 },
                new City { Id = 804, Name = "Hodeidah", CountryId = 81 },
                new City { Id = 805, Name = "Ibb", CountryId = 81 },
                new City { Id = 806, Name = "Dhamar", CountryId = 81 },
                new City { Id = 807, Name = "Mukalla", CountryId = 81 },
                new City { Id = 808, Name = "Zabid", CountryId = 81 },
                new City { Id = 809, Name = "Sa'dah", CountryId = 81 },
                new City { Id = 810, Name = "Al Bayda", CountryId = 81 },

                // Sudan (CountryId = 82)
                new City { Id = 811, Name = "Khartoum", CountryId = 82 },
                new City { Id = 812, Name = "Omdurman", CountryId = 82 },
                new City { Id = 813, Name = "Port Sudan", CountryId = 82 },
                new City { Id = 814, Name = "Kassala", CountryId = 82 },
                new City { Id = 815, Name = "El Obeid", CountryId = 82 },
                new City { Id = 816, Name = "Nyala", CountryId = 82 },
                new City { Id = 817, Name = "Wad Medani", CountryId = 82 },
                new City { Id = 818, Name = "El Fasher", CountryId = 82 },
                new City { Id = 819, Name = "Atbara", CountryId = 82 },
                new City { Id = 820, Name = "Gedaref", CountryId = 82 },

                // Ethiopia (CountryId = 83)
                new City { Id = 821, Name = "Addis Ababa", CountryId = 83 },
                new City { Id = 822, Name = "Dire Dawa", CountryId = 83 },
                new City { Id = 823, Name = "Mekelle", CountryId = 83 },
                new City { Id = 824, Name = "Gondar", CountryId = 83 },
                new City { Id = 825, Name = "Adama", CountryId = 83 },
                new City { Id = 826, Name = "Hawassa", CountryId = 83 },
                new City { Id = 827, Name = "Bahir Dar", CountryId = 83 },
                new City { Id = 828, Name = "Jimma", CountryId = 83 },
                new City { Id = 829, Name = "Dessie", CountryId = 83 },
                new City { Id = 830, Name = "Jijiga", CountryId = 83 },

                // Tanzania (CountryId = 84)
                new City { Id = 831, Name = "Dodoma", CountryId = 84 },
                new City { Id = 832, Name = "Dar es Salaam", CountryId = 84 },
                new City { Id = 833, Name = "Mwanza", CountryId = 84 },
                new City { Id = 834, Name = "Arusha", CountryId = 84 },
                new City { Id = 835, Name = "Mbeya", CountryId = 84 },
                new City { Id = 836, Name = "Zanzibar City", CountryId = 84 },
                new City { Id = 837, Name = "Tanga", CountryId = 84 },
                new City { Id = 838, Name = "Morogoro", CountryId = 84 },
                new City { Id = 839, Name = "Kigoma", CountryId = 84 },
                new City { Id = 840, Name = "Songea", CountryId = 84 },

                // Zambia (CountryId = 85)
                new City { Id = 841, Name = "Lusaka", CountryId = 85 },
                new City { Id = 842, Name = "Ndola", CountryId = 85 },
                new City { Id = 843, Name = "Kitwe", CountryId = 85 },
                new City { Id = 844, Name = "Kabwe", CountryId = 85 },
                new City { Id = 845, Name = "Chingola", CountryId = 85 },
                new City { Id = 846, Name = "Mufulira", CountryId = 85 },
                new City { Id = 847, Name = "Livingstone", CountryId = 85 },
                new City { Id = 848, Name = "Luanshya", CountryId = 85 },
                new City { Id = 849, Name = "Chipata", CountryId = 85 },
                new City { Id = 850, Name = "Kasama", CountryId = 85 },

                // Zimbabwe (CountryId = 86)
                new City { Id = 851, Name = "Harare", CountryId = 86 },
                new City { Id = 852, Name = "Bulawayo", CountryId = 86 },
                new City { Id = 853, Name = "Chitungwiza", CountryId = 86 },
                new City { Id = 854, Name = "Mutare", CountryId = 86 },
                new City { Id = 855, Name = "Gweru", CountryId = 86 },
                new City { Id = 856, Name = "Kwekwe", CountryId = 86 },
                new City { Id = 857, Name = "Kadoma", CountryId = 86 },
                new City { Id = 858, Name = "Masvingo", CountryId = 86 },
                new City { Id = 859, Name = "Chinhoyi", CountryId = 86 },
                new City { Id = 860, Name = "Bindura", CountryId = 86 },

                // Botswana (CountryId = 87)
                new City { Id = 861, Name = "Gaborone", CountryId = 87 },
                new City { Id = 862, Name = "Francistown", CountryId = 87 },
                new City { Id = 863, Name = "Molepolole", CountryId = 87 },
                new City { Id = 864, Name = "Serowe", CountryId = 87 },
                new City { Id = 865, Name = "Selibe Phikwe", CountryId = 87 },
                new City { Id = 866, Name = "Maun", CountryId = 87 },
                new City { Id = 867, Name = "Kanye", CountryId = 87 },
                new City { Id = 868, Name = "Mochudi", CountryId = 87 },
                new City { Id = 869, Name = "Lobatse", CountryId = 87 },
                new City { Id = 870, Name = "Palapye", CountryId = 87 },

                // Namibia (CountryId = 88)
                new City { Id = 871, Name = "Windhoek", CountryId = 88 },
                new City { Id = 872, Name = "Walvis Bay", CountryId = 88 },
                new City { Id = 873, Name = "Swakopmund", CountryId = 88 },
                new City { Id = 874, Name = "Rundu", CountryId = 88 },
                new City { Id = 875, Name = "Oshakati", CountryId = 88 },
                new City { Id = 876, Name = "Katima Mulilo", CountryId = 88 },
                new City { Id = 877, Name = "Otjiwarongo", CountryId = 88 },
                new City { Id = 878, Name = "Keetmanshoop", CountryId = 88 },
                new City { Id = 879, Name = "Tsumeb", CountryId = 88 },
                new City { Id = 880, Name = "Gobabis", CountryId = 88 },

                // Madagascar (CountryId = 89)
                new City { Id = 881, Name = "Antananarivo", CountryId = 89 },
                new City { Id = 882, Name = "Toamasina", CountryId = 89 },
                new City { Id = 883, Name = "Antsirabe", CountryId = 89 },
                new City { Id = 884, Name = "Fianarantsoa", CountryId = 89 },
                new City { Id = 885, Name = "Mahajanga", CountryId = 89 },
                new City { Id = 886, Name = "Toliara", CountryId = 89 },
                new City { Id = 887, Name = "Morondava", CountryId = 89 },
                new City { Id = 888, Name = "Ambatondrazaka", CountryId = 89 },
                new City { Id = 889, Name = "Manakara", CountryId = 89 },
                new City { Id = 890, Name = "Nosy Be", CountryId = 89 },

                // Papua New Guinea (CountryId = 90)
                new City { Id = 891, Name = "Port Moresby", CountryId = 90 },
                new City { Id = 892, Name = "Lae", CountryId = 90 },
                new City { Id = 893, Name = "Madang", CountryId = 90 },
                new City { Id = 894, Name = "Mount Hagen", CountryId = 90 },
                new City { Id = 895, Name = "Goroka", CountryId = 90 },
                new City { Id = 896, Name = "Rabaul", CountryId = 90 },
                new City { Id = 897, Name = "Kimbe", CountryId = 90 },
                new City { Id = 898, Name = "Wewak", CountryId = 90 },
                new City { Id = 899, Name = "Kavieng", CountryId = 90 },
                new City { Id = 900, Name = "Alotau", CountryId = 90 },

                // Fiji (CountryId = 91)
                new City { Id = 901, Name = "Suva", CountryId = 91 },
                new City { Id = 902, Name = "Nadi", CountryId = 91 },
                new City { Id = 903, Name = "Lautoka", CountryId = 91 },
                new City { Id = 904, Name = "Labasa", CountryId = 91 },
                new City { Id = 905, Name = "Ba", CountryId = 91 },
                new City { Id = 906, Name = "Levuka", CountryId = 91 },
                new City { Id = 907, Name = "Savusavu", CountryId = 91 },
                new City { Id = 908, Name = "Rakiraki", CountryId = 91 },
                new City { Id = 909, Name = "Tavua", CountryId = 91 },
                new City { Id = 910, Name = "Sigatoka", CountryId = 91 },

                // Solomon Islands (CountryId = 92)
                new City { Id = 911, Name = "Honiara", CountryId = 92 },
                new City { Id = 912, Name = "Gizo", CountryId = 92 },
                new City { Id = 913, Name = "Auki", CountryId = 92 },
                new City { Id = 914, Name = "Tulagi", CountryId = 92 },
                new City { Id = 915, Name = "Kirakira", CountryId = 92 },
                new City { Id = 916, Name = "Lata", CountryId = 92 },
                new City { Id = 917, Name = "Munda", CountryId = 92 },
                new City { Id = 918, Name = "Taro", CountryId = 92 },
                new City { Id = 919, Name = "Buala", CountryId = 92 },
                new City { Id = 920, Name = "Noro", CountryId = 92 },

                // Brunei (CountryId = 93)
                new City { Id = 921, Name = "Bandar Seri Begawan", CountryId = 93 },
                new City { Id = 922, Name = "Kuala Belait", CountryId = 93 },
                new City { Id = 923, Name = "Seria", CountryId = 93 },
                new City { Id = 924, Name = "Tutong", CountryId = 93 },
                new City { Id = 925, Name = "Bangar", CountryId = 93 },
                new City { Id = 926, Name = "Muara", CountryId = 93 },
                new City { Id = 927, Name = "Temburong", CountryId = 93 },
                new City { Id = 928, Name = "Lumut", CountryId = 93 },
                new City { Id = 929, Name = "Jerudong", CountryId = 93 },
                new City { Id = 930, Name = "Lamunin", CountryId = 93 },

                // Malawi (CountryId = 94)
                new City { Id = 931, Name = "Lilongwe", CountryId = 94 },
                new City { Id = 932, Name = "Blantyre", CountryId = 94 },
                new City { Id = 933, Name = "Mzuzu", CountryId = 94 },
                new City { Id = 934, Name = "Zomba", CountryId = 94 },
                new City { Id = 935, Name = "Kasungu", CountryId = 94 },
                new City { Id = 936, Name = "Mangochi", CountryId = 94 },
                new City { Id = 937, Name = "Karonga", CountryId = 94 },
                new City { Id = 938, Name = "Salima", CountryId = 94 },
                new City { Id = 939, Name = "Nkhotakota", CountryId = 94 },
                new City { Id = 940, Name = "Mchinji", CountryId = 94 },

                // Burundi (CountryId = 95)
                new City { Id = 941, Name = "Gitega", CountryId = 95 },
                new City { Id = 942, Name = "Ngozi", CountryId = 95 },
                new City { Id = 943, Name = "Ruyigi", CountryId = 95 },
                new City { Id = 944, Name = "Kayanza", CountryId = 95 },
                new City { Id = 945, Name = "Muyinga", CountryId = 95 },
                new City { Id = 946, Name = "Makamba", CountryId = 95 },
                new City { Id = 947, Name = "Bururi", CountryId = 95 },
                new City { Id = 948, Name = "Cibitoke", CountryId = 95 },
                new City { Id = 949, Name = "Bubanza", CountryId = 95 },
                new City { Id = 950, Name = "Karuzi", CountryId = 95 },

                // Rwanda (CountryId = 96)
                new City { Id = 951, Name = "Kigali", CountryId = 96 },
                new City { Id = 952, Name = "Gisenyi", CountryId = 96 },
                new City { Id = 953, Name = "Ruhengeri", CountryId = 96 },
                new City { Id = 954, Name = "Butare", CountryId = 96 },
                new City { Id = 955, Name = "Muhanga", CountryId = 96 },
                new City { Id = 956, Name = "Byumba", CountryId = 96 },
                new City { Id = 957, Name = "Cyangugu", CountryId = 96 },
                new City { Id = 958, Name = "Nyanza", CountryId = 96 },
                new City { Id = 959, Name = "Kibuye", CountryId = 96 },
                new City { Id = 960, Name = "Rwamagana", CountryId = 96 },

                // Ivory Coast (CountryId = 97)
                new City { Id = 961, Name = "Abidjan", CountryId = 97 },
                new City { Id = 962, Name = "Yamoussoukro", CountryId = 97 },
                new City { Id = 963, Name = "Bouaké", CountryId = 97 },
                new City { Id = 964, Name = "Daloa", CountryId = 97 },
                new City { Id = 965, Name = "Korhogo", CountryId = 97 },
                new City { Id = 966, Name = "San-Pédro", CountryId = 97 },
                new City { Id = 967, Name = "Man", CountryId = 97 },
                new City { Id = 968, Name = "Gagnoa", CountryId = 97 },
                new City { Id = 969, Name = "Abengourou", CountryId = 97 },
                new City { Id = 970, Name = "Divo", CountryId = 97 },

                // Senegal (CountryId = 98)
                new City { Id = 971, Name = "Dakar", CountryId = 98 },
                new City { Id = 972, Name = "Thiès", CountryId = 98 },
                new City { Id = 973, Name = "Saint-Louis", CountryId = 98 },
                new City { Id = 974, Name = "Kaolack", CountryId = 98 },
                new City { Id = 975, Name = "Ziguinchor", CountryId = 98 },
                new City { Id = 976, Name = "Rufisque", CountryId = 98 },
                new City { Id = 977, Name = "Mbour", CountryId = 98 },
                new City { Id = 978, Name = "Diourbel", CountryId = 98 },
                new City { Id = 979, Name = "Louga", CountryId = 98 },
                new City { Id = 980, Name = "Tambacounda", CountryId = 98 },

                // Ghana (CountryId = 99)
                new City { Id = 981, Name = "Accra", CountryId = 99 },
                new City { Id = 982, Name = "Kumasi", CountryId = 99 },
                new City { Id = 983, Name = "Tamale", CountryId = 99 },
                new City { Id = 984, Name = "Sekondi-Takoradi", CountryId = 99 },
                new City { Id = 985, Name = "Tema", CountryId = 99 },
                new City { Id = 986, Name = "Cape Coast", CountryId = 99 },
                new City { Id = 987, Name = "Koforidua", CountryId = 99 },
                new City { Id = 988, Name = "Wa", CountryId = 99 },
                new City { Id = 989, Name = "Ho", CountryId = 99 },
                new City { Id = 990, Name = "Sunyani", CountryId = 99 },

                // Cameroon (CountryId = 100)
                new City { Id = 991, Name = "Yaoundé", CountryId = 100 },
                new City { Id = 992, Name = "Douala", CountryId = 100 },
                new City { Id = 993, Name = "Bamenda", CountryId = 100 },
                new City { Id = 994, Name = "Garoua", CountryId = 100 },
                new City { Id = 995, Name = "Bafoussam", CountryId = 100 },
                new City { Id = 996, Name = "Maroua", CountryId = 100 },
                new City { Id = 997, Name = "Ngaoundéré", CountryId = 100 },
                new City { Id = 998, Name = "Kumba", CountryId = 100 },
                new City { Id = 999, Name = "Buea", CountryId = 100 },
                new City { Id = 1000, Name = "Limbe", CountryId = 100 }


            };
        }
    }
}
