using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Mottrist.Domain.Entities.CarDetails;

namespace Mottrist.Repository.EntityFrameworkCore.Configurations.VehiclesSchemaConfiguration
{
    public class BrandConfiguration : IEntityTypeConfiguration<Brand>
    {
        public void Configure(EntityTypeBuilder<Brand> builder)
        {
            builder.HasKey(b => b.Id);

            builder.Property(b => b.Name)
                   .IsRequired();

            builder.ToTable("Brands", schema: "Vehicles");

            // Seed data
            builder.HasData(GetBrands());
        }
        private List<Brand> GetBrands()
        {
            return new List<Brand>()
    {
        new Brand { Id = 1, Name = "Toyota" },
        new Brand { Id = 2, Name = "Honda" },
        new Brand { Id = 3, Name = "Ford" },
        new Brand { Id = 4, Name = "Chevrolet" },
        new Brand { Id = 5, Name = "Nissan" },
        new Brand { Id = 6, Name = "Volkswagen" },
        new Brand { Id = 7, Name = "BMW" },
        new Brand { Id = 8, Name = "Mercedes-Benz" },
        new Brand { Id = 9, Name = "Audi" },
        new Brand { Id = 10, Name = "Hyundai" },
        new Brand { Id = 11, Name = "Kia" },
        new Brand { Id = 12, Name = "Renault" },
        new Brand { Id = 13, Name = "Peugeot" },
        new Brand { Id = 14, Name = "Fiat" },
        new Brand { Id = 15, Name = "Mazda" },
        new Brand { Id = 16, Name = "Subaru" },
        new Brand { Id = 17, Name = "Suzuki" },
        new Brand { Id = 18, Name = "Mitsubishi" },
        new Brand { Id = 19, Name = "Volvo" },
        new Brand { Id = 20, Name = "Tesla" },
        new Brand { Id = 21, Name = "Jeep" },
        new Brand { Id = 22, Name = "Land Rover" },
        new Brand { Id = 23, Name = "Porsche" },
        new Brand { Id = 24, Name = "Ferrari" },
        new Brand { Id = 25, Name = "Lamborghini" },
        new Brand { Id = 26, Name = "Aston Martin" },
        new Brand { Id = 27, Name = "Bentley" },
        new Brand { Id = 28, Name = "Rolls-Royce" },
        new Brand { Id = 29, Name = "Bugatti" },
        new Brand { Id = 30, Name = "Chrysler" },
        new Brand { Id = 31, Name = "Dodge" },
        new Brand { Id = 32, Name = "GMC" },
        new Brand { Id = 33, Name = "Cadillac" },
        new Brand { Id = 34, Name = "Lincoln" },
        new Brand { Id = 35, Name = "Buick" },
        new Brand { Id = 36, Name = "Opel" },
        new Brand { Id = 37, Name = "Saab" },
        new Brand { Id = 38, Name = "Skoda" },
        new Brand { Id = 39, Name = "Seat" },
        new Brand { Id = 40, Name = "Citroën" },
        new Brand { Id = 41, Name = "Alfa Romeo" },
        new Brand { Id = 42, Name = "Lancia" },
        new Brand { Id = 43, Name = "Daewoo" },
        new Brand { Id = 44, Name = "SsangYong" },
        new Brand { Id = 45, Name = "Tata Motors" },
        new Brand { Id = 46, Name = "Mahindra" },
        new Brand { Id = 47, Name = "Hindustan Motors" },
        new Brand { Id = 48, Name = "Maruti Suzuki" },
        new Brand { Id = 49, Name = "Isuzu" },
        new Brand { Id = 50, Name = "Daihatsu" },
        new Brand { Id = 51, Name = "Hino Motors" },
        new Brand { Id = 52, Name = "Lexus" },
        new Brand { Id = 53, Name = "Infiniti" },
        new Brand { Id = 54, Name = "Acura" },
        new Brand { Id = 55, Name = "Scion" },
        new Brand { Id = 56, Name = "Genesis" },
        new Brand { Id = 57, Name = "Smart" },
        new Brand { Id = 58, Name = "Mini" },
        new Brand { Id = 59, Name = "Jaguar" },
        new Brand { Id = 60, Name = "Lotus" },
        new Brand { Id = 61, Name = "MG" },
        new Brand { Id = 62, Name = "Rover" },
        new Brand { Id = 63, Name = "Austin" },
        new Brand { Id = 64, Name = "Morris" },
        new Brand { Id = 65, Name = "Vauxhall" },
        new Brand { Id = 66, Name = "Holden" },
        new Brand { Id = 67, Name = "FPV" },
        new Brand { Id = 68, Name = "HSV" },
        new Brand { Id = 69, Name = "Proton" },
        new Brand { Id = 70, Name = "Perodua" },
        new Brand { Id = 71, Name = "Chery" },
        new Brand { Id = 72, Name = "Geely" },
        new Brand { Id = 73, Name = "BYD" },
        new Brand { Id = 74, Name = "Great Wall Motors" },
        new Brand { Id = 75, Name = "FAW" },
        new Brand { Id = 76, Name = "Changan" },
        new Brand { Id = 77, Name = "Dongfeng" },
        new Brand { Id = 78, Name = "BAIC" },
        new Brand { Id = 79, Name = "JAC" },
        new Brand { Id = 80, Name = "Zotye" },
        new Brand { Id = 81, Name = "Landwind" },
        new Brand { Id = 82, Name = "Hawtai" },
        new Brand { Id = 83, Name = "Soueast" },
        new Brand { Id = 84, Name = "Brilliance" },
        new Brand { Id = 85, Name = "Roewe" },
        new Brand { Id = 86, Name = "MG Motor India" },
        new Brand { Id = 87, Name = "Force Motors" },
        new Brand { Id = 88, Name = "Premier Ltd." },
        new Brand { Id = 89, Name = "Ram" }, // New USA brand
        new Brand { Id = 90, Name = "SRT" }, // New USA brand
        new Brand { Id = 91, Name = "Hummer" }, // New USA brand
        new Brand { Id = 92, Name = "SML Isuzu" },
        new Brand { Id = 93, Name = "Ashok Leyland" },
        new Brand { Id = 94, Name = "Eicher Motors" },
        new Brand { Id = 95, Name = "Piaggio" },
        new Brand { Id = 96, Name = "Bajaj Auto" },
        new Brand { Id = 97, Name = "TVS Motors" },
        new Brand { Id = 98, Name = "Hero MotoCorp" },
        new Brand { Id = 99, Name = "Yamaha Motor Company" },
        new Brand { Id = 100, Name = "Suzuki Motorcycles" },
        new Brand { Id = 101, Name = "Kawasaki" },
        new Brand { Id = 102, Name = "Ducati" },
        new Brand { Id = 103, Name = "Harley-Davidson" },
        new Brand { Id = 104, Name = "Triumph" },
        new Brand { Id = 105, Name = "KTM" },
        new Brand { Id = 106, Name = "Aprilia" },
        new Brand { Id = 107, Name = "Vespa" },
        new Brand { Id = 108, Name = "Royal Enfield" },
        new Brand { Id = 109, Name = "Benelli" },
        new Brand { Id = 110, Name = "Moto Guzzi" },
        new Brand { Id = 111, Name = "Husqvarna" },
        new Brand { Id = 112, Name = "Indian Motorcycle" },
        new Brand { Id = 113, Name = "MV Agusta" },
        new Brand { Id = 114, Name = "Bimota" },
        new Brand { Id = 115, Name = "Norton" },
        new Brand { Id = 116, Name = "Zero Motorcycles" },
        new Brand { Id = 117, Name = "CFMoto" },
        new Brand { Id = 118, Name = "Ural" },
        new Brand { Id = 119, Name = "Victory Motorcycles" },
        new Brand { Id = 120, Name = "Sym" },
        new Brand { Id = 121, Name = "Kymco" },
        new Brand { Id = 122, Name = "PGO Scooters" },
        new Brand { Id = 123, Name = "Lifan" },
        new Brand { Id = 124, Name = "Haojue" },
        new Brand { Id = 125, Name = "QJMotor" },
        new Brand { Id = 126, Name = "Zongshen" },
        new Brand { Id = 127, Name = "Loncin" },
        new Brand { Id = 128, Name = "Dayun" },
        new Brand { Id = 129, Name = "Jincheng" },
        new Brand { Id = 130, Name = "Shineray" },
        new Brand { Id = 131, Name = "Daelim" },
        new Brand { Id = 132, Name = "Hyosung" },
        new Brand { Id = 133, Name = "Keeway" },
        new Brand { Id = 134, Name = "Super Soco" },
        new Brand { Id = 135, Name = "Energica" },
        new Brand { Id = 136, Name = "Arcimoto" },
        new Brand { Id = 137, Name = "Rivian" },
        new Brand { Id = 138, Name = "Lucid Motors" },
        new Brand { Id = 139, Name = "Fisker" },
        new Brand { Id = 140, Name = "NIO" },
        new Brand { Id = 141, Name = "XPeng" },
        new Brand { Id = 142, Name = "Li Auto" },
        new Brand { Id = 143, Name = "Polestar" },
        new Brand { Id = 144, Name = "VinFast" },
        new Brand { Id = 145, Name = "Sono Motors" },
        new Brand { Id = 146, Name = "Lightyear" },
        new Brand { Id = 147, Name = "Aptera Motors" },
        new Brand { Id = 148, Name = "Faraday Future" },
        new Brand { Id = 149, Name = "Lordstown Motors" },
        new Brand { Id = 150, Name = "Canoo" },
        new Brand { Id = 151, Name = "Bollinger Motors" },
        new Brand { Id = 152, Name = "ElectraMeccanica" },
        new Brand { Id = 153, Name = "Pininfarina" },
        new Brand { Id = 154, Name = "Maserati" },
        new Brand { Id = 155, Name = "McLaren" },
        new Brand { Id = 156, Name = "Pagani" },
        new Brand { Id = 157, Name = "Koenigsegg" },
        new Brand { Id = 158, Name = "Rimac" },
        new Brand { Id = 159, Name = "Spyker" },
        new Brand { Id = 160, Name = "De Tomaso" },
        new Brand { Id = 161, Name = "Hispano Suiza" },
        new Brand { Id = 162, Name = "DS Automobiles" }, // New European brand
        new Brand { Id = 163, Name = "Saleen" }, // New USA brand
        new Brand { Id = 164, Name = "Iveco" },
        new Brand { Id = 165, Name = "MAN" },
        new Brand { Id = 166, Name = "Scania" },
        new Brand { Id = 167, Name = "DAF" },
        new Brand { Id = 168, Name = "Navistar" },
        new Brand { Id = 169, Name = "Paccar" },
        new Brand { Id = 170, Name = "Kenworth" },
        new Brand { Id = 171, Name = "Peterbilt" },
        new Brand { Id = 172, Name = "Freightliner" },
        new Brand { Id = 173, Name = "Mack Trucks" },
        new Brand { Id = 174, Name = "Western Star" },
        new Brand { Id = 175, Name = "Volvo Trucks" },
        new Brand { Id = 176, Name = "Renault Trucks" },
        new Brand { Id = 177, Name = "Tatra" },
        new Brand { Id = 178, Name = "Kamaz" },
        new Brand { Id = 179, Name = "UralAZ" },
        new Brand { Id = 180, Name = "GAZ" },
        new Brand { Id = 181, Name = "ZIL" },
        new Brand { Id = 182, Name = "MAZ" },
        new Brand { Id = 183, Name = "KrAZ" },
        new Brand { Id = 184, Name = "BelAZ" },
        new Brand { Id = 185, Name = "Sinotruk" },
        new Brand { Id = 186, Name = "Foton" },
        new Brand { Id = 187, Name = "Shacman" },
        new Brand { Id = 188, Name = "Howo" },
        new Brand { Id = 189, Name = "Yutong" },
        new Brand { Id = 190, Name = "King Long" },
        new Brand { Id = 191, Name = "Golden Dragon" },
        new Brand { Id = 192, Name = "Higer" },
        new Brand { Id = 193, Name = "Ankai" },
        new Brand { Id = 194, Name = "Sollers" },
        new Brand { Id = 195, Name = "Avtovaz" },
        new Brand { Id = 196, Name = "Lada" },
        new Brand { Id = 197, Name = "UAZ" },
        new Brand { Id = 198, Name = "Moskvitch" },
        new Brand { Id = 199, Name = "Dacia" }, // New European brand
        new Brand { Id = 200, Name = "International Harvester" } // New USA brand
    };
        }
    }
}