using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Mottrist.Domain.Entities.CarDetails;

namespace Mottrist.Repository.EntityFrameworkCore.Configurations.VehiclesSchemaConfiguration
{
    public class ColorConfiguration : IEntityTypeConfiguration<Color>
    {
        public void Configure(EntityTypeBuilder<Color> builder)
        {
            builder.HasKey(c => c.Id);

            builder.Property(c => c.Name)
                   .IsRequired()
                   .HasMaxLength(50);

            builder.ToTable("Colors", schema: "Vehicles");

            // Seed data
            builder.HasData(GetColors());

        }
        private List<Color> GetColors()
        {
            return new List<Color>
    {
        new Color { Id = 1, Name = "Red" },
        new Color { Id = 2, Name = "Blue" },
        new Color { Id = 3, Name = "Green" },
        new Color { Id = 4, Name = "Black" },
        new Color { Id = 5, Name = "White" },
        new Color { Id = 6, Name = "Silver" },
        new Color { Id = 7, Name = "Gray" },
        new Color { Id = 8, Name = "Yellow" },
        new Color { Id = 9, Name = "Brown" },
        new Color { Id = 10, Name = "Purple" },
        new Color { Id = 11, Name = "Candy Apple Red" },
        new Color { Id = 12, Name = "Midnight Blue" },
        new Color { Id = 13, Name = "Forest Green" },
        new Color { Id = 14, Name = "Jet Black" },
        new Color { Id = 15, Name = "Pearl White" },
        new Color { Id = 16, Name = "Metallic Silver" },
        new Color { Id = 17, Name = "Slate Gray" },
        new Color { Id = 18, Name = "Sunburst Yellow" },
        new Color { Id = 19, Name = "Mocha Brown" },
        new Color { Id = 20, Name = "Vivid Purple" },
        new Color { Id = 21, Name = "Ruby Red" },
        new Color { Id = 22, Name = "Sapphire Blue" },
        new Color { Id = 23, Name = "Emerald Green" },
        new Color { Id = 24, Name = "Obsidian Black" },
        new Color { Id = 25, Name = "Ivory White" },
        new Color { Id = 26, Name = "Titanium Silver" },
        new Color { Id = 27, Name = "Charcoal Gray" },
        new Color { Id = 28, Name = "Canary Yellow" },
        new Color { Id = 29, Name = "Chocolate Brown" },
        new Color { Id = 30, Name = "Amethyst Purple" },
        new Color { Id = 31, Name = "Crimson Red" },
        new Color { Id = 32, Name = "Navy Blue" },
        new Color { Id = 33, Name = "Olive Green" },
        new Color { Id = 34, Name = "Onyx Black" },
        new Color { Id = 35, Name = "Cream White" },
        new Color { Id = 36, Name = "Platinum Silver" },
        new Color { Id = 37, Name = "Gunmetal Gray" },
        new Color { Id = 38, Name = "Lemon Yellow" },
        new Color { Id = 39, Name = "Espresso Brown" },
        new Color { Id = 40, Name = "Plum Purple" },
        new Color { Id = 41, Name = "Fire Engine Red" },
        new Color { Id = 42, Name = "Sky Blue" },
        new Color { Id = 43, Name = "Lime Green" },
        new Color { Id = 44, Name = "Matte Black" },
        new Color { Id = 45, Name = "Snow White" },
        new Color { Id = 46, Name = "Brushed Silver" },
        new Color { Id = 47, Name = "Steel Gray" },
        new Color { Id = 48, Name = "Mustard Yellow" },
        new Color { Id = 49, Name = "Caramel Brown" },
        new Color { Id = 50, Name = "Violet Purple" },
        new Color { Id = 51, Name = "Cherry Red" },
        new Color { Id = 52, Name = "Cobalt Blue" },
        new Color { Id = 53, Name = "Mint Green" },
        new Color { Id = 54, Name = "Ebony Black" },
        new Color { Id = 55, Name = "Alabaster White" },
        new Color { Id = 56, Name = "Chrome Silver" },
        new Color { Id = 57, Name = "Pewter Gray" },
        new Color { Id = 58, Name = "Saffron Yellow" },
        new Color { Id = 59, Name = "Walnut Brown" },
        new Color { Id = 60, Name = "Lilac Purple" },
        new Color { Id = 61, Name = "Scarlet Red" },
        new Color { Id = 62, Name = "Aqua Blue" },
        new Color { Id = 63, Name = "Jade Green" },
        new Color { Id = 64, Name = "Satin Black" },
        new Color { Id = 65, Name = "Chalk White" },
        new Color { Id = 66, Name = "Liquid Silver" },
        new Color { Id = 67, Name = "Iron Gray" },
        new Color { Id = 68, Name = "Amber Yellow" },
        new Color { Id = 69, Name = "Hazelnut Brown" },
        new Color { Id = 70, Name = "Orchid Purple" },
        new Color { Id = 71, Name = "Burgundy Red" },
        new Color { Id = 72, Name = "Turquoise Blue" },
        new Color { Id = 73, Name = "Sage Green" },
        new Color { Id = 74, Name = "Gloss Black" },
        new Color { Id = 75, Name = "Eggshell White" },
        new Color { Id = 76, Name = "Polished Silver" },
        new Color { Id = 77, Name = "Ash Gray" },
        new Color { Id = 78, Name = "Golden Yellow" },
        new Color { Id = 79, Name = "Cocoa Brown" },
        new Color { Id = 80, Name = "Magenta Purple" },
        new Color { Id = 81, Name = "Maroon Red" },
        new Color { Id = 82, Name = "Cerulean Blue" },
        new Color { Id = 83, Name = "Pine Green" },
        new Color { Id = 84, Name = "Raven Black" },
        new Color { Id = 85, Name = "Porcelain White" },
        new Color { Id = 86, Name = "Sterling Silver" },
        new Color { Id = 87, Name = "Smoke Gray" },
        new Color { Id = 88, Name = "Honey Yellow" },
        new Color { Id = 89, Name = "Truffle Brown" },
        new Color { Id = 90, Name = "Fuchsia Purple" },
        new Color { Id = 91, Name = "Coral Red" },
        new Color { Id = 92, Name = "Teal Blue" },
        new Color { Id = 93, Name = "Moss Green" },
        new Color { Id = 94, Name = "Carbon Black" },
        new Color { Id = 95, Name = "Milky White" },
        new Color { Id = 96, Name = "Quicksilver" },
        new Color { Id = 97, Name = "Granite Gray" },
        new Color { Id = 98, Name = "Butter Yellow" },
        new Color { Id = 99, Name = "Sienna Brown" },
        new Color { Id = 100, Name = "Indigo Purple" },
        new Color { Id = 101, Name = "Vermilion Red" },
        new Color { Id = 102, Name = "Azure Blue" },
        new Color { Id = 103, Name = "Fern Green" },
        new Color { Id = 104, Name = "Midnight Black" },
        new Color { Id = 105, Name = "Opal White" },
        new Color { Id = 106, Name = "Iridescent Silver" },
        new Color { Id = 107, Name = "Basalt Gray" },
        new Color { Id = 108, Name = "Dandelion Yellow" },
        new Color { Id = 109, Name = "Mahogany Brown" },
        new Color { Id = 110, Name = "Eggplant Purple" },
        new Color { Id = 111, Name = "Garnet Red" },
        new Color { Id = 112, Name = "Ocean Blue" },
        new Color { Id = 113, Name = "Kelly Green" },
        new Color { Id = 114, Name = "Shadow Black" },
        new Color { Id = 115, Name = "Frost White" },
        new Color { Id = 116, Name = "Mercury Silver" },
        new Color { Id = 117, Name = "Flint Gray" },
        new Color { Id = 118, Name = "Mango Yellow" },
        new Color { Id = 119, Name = "Cedar Brown" },
        new Color { Id = 120, Name = "Lavender Purple" },
        new Color { Id = 121, Name = "Brick Red" },
        new Color { Id = 122, Name = "Denim Blue" },
        new Color { Id = 123, Name = "Shamrock Green" },
        new Color { Id = 124, Name = "Pitch Black" },
        new Color { Id = 125, Name = "Linen White" },
        new Color { Id = 126, Name = "Aluminum Silver" },
        new Color { Id = 127, Name = "Storm Gray" },
        new Color { Id = 128, Name = "Tangerine Yellow" },
        new Color { Id = 129, Name = "Teak Brown" },
        new Color { Id = 130, Name = "Mauve Purple" },
        new Color { Id = 131, Name = "Rose Red" },
        new Color { Id = 132, Name = "Glacier Blue" },
        new Color { Id = 133, Name = "Cypress Green" },
        new Color { Id = 134, Name = "Coal Black" },
        new Color { Id = 135, Name = "Marble White" },
        new Color { Id = 136, Name = "Nickel Silver" },
        new Color { Id = 137, Name = "Mist Gray" },
        new Color { Id = 138, Name = "Banana Yellow" },
        new Color { Id = 139, Name = "Pecan Brown" },
        new Color { Id = 140, Name = "Grape Purple" },
        new Color { Id = 141, Name = "Salmon Red" },
        new Color { Id = 142, Name = "Lagoon Blue" },
        new Color { Id = 143, Name = "Spruce Green" },
        new Color { Id = 144, Name = "Velvet Black" },
        new Color { Id = 145, Name = "Bone White" },
        new Color { Id = 146, Name = "Pewter Silver" },
        new Color { Id = 147, Name = "Fog Gray" },
        new Color { Id = 148, Name = "Pumpkin Yellow" },
        new Color { Id = 149, Name = "Oak Brown" },
        new Color { Id = 150, Name = "Berry Purple" },
        new Color { Id = 151, Name = "Tomato Red" },
        new Color { Id = 152, Name = "Powder Blue" },
        new Color { Id = 153, Name = "Avocado Green" },
        new Color { Id = 154, Name = "Smoky Black" },
        new Color { Id = 155, Name = "Cotton White" },
        new Color { Id = 156, Name = "Zinc Silver" },
        new Color { Id = 157, Name = "Cloud Gray" },
        new Color { Id = 158, Name = "Apricot Yellow" },
        new Color { Id = 159, Name = "Chestnut Brown" },
        new Color { Id = 160, Name = "Raspberry Purple" },
        new Color { Id = 161, Name = "Blood Red" },
        new Color { Id = 162, Name = "Periwinkle Blue" },
        new Color { Id = 163, Name = "Basil Green" },
        new Color { Id = 164, Name = "Graphite Black" },
        new Color { Id = 165, Name = "Seashell White" },
        new Color { Id = 166, Name = "Tin Silver" },
        new Color { Id = 167, Name = "Dusk Gray" },
        new Color { Id = 168, Name = "Peach Yellow" },
        new Color { Id = 169, Name = "Maple Brown" },
        new Color { Id = 170, Name = "Blackberry Purple" },
        new Color { Id = 171, Name = "Cardinal Red" },
        new Color { Id = 172, Name = "Cornflower Blue" },
        new Color { Id = 173, Name = "Thyme Green" },
        new Color { Id = 174, Name = "Anthracite Black" },
        new Color { Id = 175, Name = "Vanilla White" },
        new Color { Id = 176, Name = "Steel Silver" },
        new Color { Id = 177, Name = "Haze Gray" },
        new Color { Id = 178, Name = "Citron Yellow" },
        new Color { Id = 179, Name = "Acorn Brown" },
        new Color { Id = 180, Name = "Mulberry Purple" },
        new Color { Id = 181, Name = "Chili Red" },
        new Color { Id = 182, Name = "Robin Egg Blue" },
        new Color { Id = 183, Name = "Celery Green" },
        new Color { Id = 184, Name = "Soot Black" },
        new Color { Id = 185, Name = "Parchment White" },
        new Color { Id = 186, Name = "Cadmium Silver" },
        new Color { Id = 187, Name = "Shale Gray" },
        new Color { Id = 188, Name = "Marigold Yellow" },
        new Color { Id = 189, Name = "Bark Brown" },
        new Color { Id = 190, Name = "Boysenberry Purple" },
        new Color { Id = 191, Name = "Poppy Red" },
        new Color { Id = 192, Name = "Baby Blue" },
        new Color { Id = 193, Name = "Pistachio Green" },
        new Color { Id = 194, Name = "Ink Black" },
        new Color { Id = 195, Name = "Quartz White" },
        new Color { Id = 196, Name = "Mithril Silver" },
        new Color { Id = 197, Name = "Cinder Gray" },
        new Color { Id = 198, Name = "Ginger Yellow" },
        new Color { Id = 199, Name = "Saddle Brown" },
        new Color { Id = 200, Name = "Concord Purple" },
        new Color { Id = 201, Name = "Sangria Red" },
        new Color { Id = 202, Name = "Peacock Blue" },
        new Color { Id = 203, Name = "Parrot Green" },
        new Color { Id = 204, Name = "Caviar Black" },
        new Color { Id = 205, Name = "Lace White" },
        new Color { Id = 206, Name = "Bismuth Silver" },
        new Color { Id = 207, Name = "Driftwood Gray" },
        new Color { Id = 208, Name = "Papaya Yellow" },
        new Color { Id = 209, Name = "Rosewood Brown" },
        new Color { Id = 210, Name = "Huckleberry Purple" },
        new Color { Id = 211, Name = "Flamingo Pink" },
        new Color { Id = 212, Name = "Arctic Blue" },
        new Color { Id = 213, Name = "Seafoam Green" },
        new Color { Id = 214, Name = "Phantom Black" },
        new Color { Id = 215, Name = "Dove White" },
        new Color { Id = 216, Name = "Tungsten Silver" },
        new Color { Id = 217, Name = "Boulder Gray" },
        new Color { Id = 218, Name = "Nectarine Orange" },
        new Color { Id = 219, Name = "Ebony Brown" },
        new Color { Id = 220, Name = "Wisteria Purple" }
    };
        }
    }
   
}